#pragma save_binary
#include <ansi.h>
inherit SKILL;

#define TIME 1000
#define EXP 40
#define POT 12

mapping *quest = ({
([      "quest":                "打铁僧",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "打铁僧",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "扫地僧",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "赵狗儿",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "赵狗儿",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "波斯商人",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "波斯商人",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "波斯长袍",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "阿拉伯弯刀",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "阿拉木罕",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "阿拉木罕",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "长鞭",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "维吾尔族长袍",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "伊犁马",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "飞龙帮众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "飞龙帮众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "管家",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "管家",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "镖头",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "镖头",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "衙役",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "衙役",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "衙役服",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "流氓头",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "王小二",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "王小二",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "关阿牛",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "关阿牛",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "索狗儿",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "索狗儿",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "知客道长",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "知客道长",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "老者",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "老者",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "道士",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "道士",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "黄色道袍",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "小喽罗",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "伐木道长",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "伐木道长",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "农妇",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "农妇",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "门卫",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "门卫",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "大刀",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "官兵",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "官兵",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "军服",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "林平之",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "林平之",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "趟子手",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "趟子手",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "挑夫",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "挑夫",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "赵老板",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "赵老板",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "崔掌柜",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "崔掌柜",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "李大哥",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "李大哥",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "水老板",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "水老板",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "陈叁",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "陈叁",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "王德",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "王德",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}



