#pragma save_binary
#include <ansi.h>
inherit SKILL;

#define TIME 1000
#define EXP 35
#define POT 9

mapping *quest = ({
([      "quest":                "挑夫",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "挑夫",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "香客",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "香客",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "小贩",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "小贩",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "小孩",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "小孩",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "净觉",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "净觉",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "净难",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "净难",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "净苦",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "净苦",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "游客",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "游客",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "牧羊人",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "牧羊人",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "羊鞭",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "厚土旗众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "厚土旗众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "穷汉",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "穷汉",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "农妇",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "农妇",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "樵夫",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "樵夫",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "柴刀",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "张二楞",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "张二楞",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "大狼狗",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "大狼狗",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "狗皮",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "流氓",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                YEL"穷小贩"NOR,               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                YEL"穷小贩"NOR,               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "阿庆嫂",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "阿庆嫂",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "老农",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "老农",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),


([      "quest":                "民女",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "民女",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "商人",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "商人",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "小童",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "小童",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "沙弥",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "沙弥",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "星宿派号手",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "星宿派鼓手",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "星宿派钹手",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "巨木旗众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "巨木旗众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "烈火旗众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "烈火旗众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "锐金旗众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "锐金旗众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "洪水旗众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "洪水旗众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "阿凡提",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "阿凡提",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "铜号",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "铜鼓",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "铜钹 ",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}





