#pragma save_binary
#include <ansi.h>
inherit SKILL;

#define TIME 1000
#define EXP 140
#define POT 36

mapping *quest = ({
([      "quest":                "扫地老僧",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "扫地老僧",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "渡难",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "渡难",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "渡劫",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "渡劫",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "渡厄",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "渡厄",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "高长老",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "高长老",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "矮长老",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "矮长老",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "丁春秋",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "龙华天",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "龙华天",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                RED "郭靖" NOR,               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                RED "郭靖" NOR,               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "黄蓉",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "黄蓉",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "周伯通",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "周伯通",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "小龙女",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "小龙女",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "杨女",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "杨女",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),


([      "quest":                "铃索",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "杨啸天",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "杨啸天",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "岳不群",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "岳不群",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "白色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "宁中则",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "宁中则",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "紫色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "梁长老",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "梁长老",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "彭有敬",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "彭有敬",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "鲁有脚",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "鲁有脚",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "简长老",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "简长老",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "柳随风",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "柳随风",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "梁柳鹤",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "梁柳鹤",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "杀手剑",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                YEL"射雕英雄传"NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "伏魔刀",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "金刚罩",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "菩提子",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "软猬甲",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "金花",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "王语嫣",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "王语嫣",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "黄钟公",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "古琴",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "黑白子",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "玄铁棋秤",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "秃笔翁",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "判官笔",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "丹青生",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "丁坚",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "吴三桂",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                RED "英雄剑" NOR ,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "护院总武师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                YEL "洋枪" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "金丝甲",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "鱼肠刺",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "任我行",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
