#include <ansi.h> 
 
mapping *wheres=({
      (["chinese":                "比武场",
       "weizhi" :              "/d/city/biwuchang",]),  
      (["chinese":                "扬州青竹林",
       "weizhi" :              "/d/city/ml2",]),  
       (["chinese":                "铁枪庙 ",
       "weizhi" :              "/d/quanzhou/tieqiang",]),
       (["chinese":                "泉州码头",
       "weizhi" :              "/d/diaoyudao/matou0",]),
        (["chinese":                "南天门",
       "weizhi" :              "/d/taishan/nantian",]),
        (["chinese":                "村中小路",
        "weizhi" :              "/d/riyuejiao/cunlu1",]),
       (["chinese":                "杀手帮大道",
       "weizhi" :               "/d/pker/dadao23",]),
     (["chinese":                 "六盘山 ",
       "weizhi" :               "/d/xingxiu/xxroad3",]),
     (["chinese":                "星宿海",
       "weizhi" :              "/d/xingxiu/xxh2",]),
     (["chinese":                "绿柳山庄大门",
       "weizhi" :              "/d/mingjiao/lvliu1",]),
     (["chinese":                "了望塔",
       "weizhi" :              "/d/mingjiao/liaowang",]),
     (["chinese":                "巨木坛",
       "weizhi" :              "/d/mingjiao/jm-tan",]),
     (["chinese":                "松木屋",
       "weizhi" :              "/d/dali/muwu",]),
     (["chinese":                "澜沧江畔",
       "weizhi" :              "/d/dali/jiangpan",]),  
      (["chinese":                "里屋",
       "weizhi" :              "/d/xiangyang/liwu",]),  
      (["chinese":                "襄阳东门",
       "weizhi" :              "/d/xiangyang/egate",]), 
      (["chinese":                "菜园",
       "weizhi" :              "/d/xiangyang/caiyuan",]), 
      (["chinese":                "半山坡",
       "weizhi" :              "/d/xiangyang/eroad2",]), 
      (["chinese":                "黄土路 ",
       "weizhi" :              "/d/wudang/wdroad8",]), 
      (["chinese":                "后山小院",
       "weizhi" :              "/d/wudang/xiaoyuan",]), 
      (["chinese":                "北天门",
       "weizhi" :              "/d/taishan/beitian",]), 
      (["chinese":                "斗母宫",
       "weizhi" :              "/d/taishan/doumo",]), 
      (["chinese":                "桃花大厅",
       "weizhi" :              "/d/taohuadao/dating",]), 
      (["chinese":                "桃花走廊",
       "weizhi" :              "/d/taohuadao/zoulang",]), 
      (["chinese":                "王子寝宫",
       "weizhi" :              "/d/lingzhou/wangzi",]), 
      (["chinese":                "琴房",
       "weizhi" :              "/d/lingzhou/qinfang",]), 
      (["chinese":                "翠玉屏风",
       "weizhi" :              "/d/pingxiwangfu/pingfeng",]), 
      (["chinese":                "独尊厅 ",
       "weizhi" :              "/d/lingjiu/zhengting",]),
      (["chinese":                "少林寺石阶",
       "weizhi" :              "/d/shaolin/shijie4",]),
      (["chinese":                "戏凤阁 ",
       "weizhi" :              "/d/lingjiu/liangong",]),
      (["chinese":                "华山猢狲愁",
       "weizhi" :              "/d/huashan/husun",]),
      (["chinese":                "华山玉女峰",
       "weizhi" :              "/d/huashan/yunu",]),
      (["chinese":                "灵鹫山路 ",
       "weizhi" :              "/d/lingjiu/shanlu1",]),
      (["chinese":                "三清殿 ",
       "weizhi" :              "/d/quanzhen/sanqingdian",]),
      (["chinese":                "校经房",
       "weizhi" :              "/d/quanzhen/jiaojf",]),
      (["chinese":                "钟阁",
       "weizhi" :              "/d/quanzhen/zhongge",]),
      (["chinese":                "墓道",
       "weizhi" :              "/d/gumu/zoudao2",]),
      (["chinese":                "古墓侧室",
       "weizhi" :              "/d/gumu/ceshi",]),
      (["chinese":                "少林寺山门殿",
       "weizhi" :              "/d/shaolin/smdian",]),
      (["chinese":                "少林寺走廊",
       "weizhi" :              "/d/shaolin/zoulang7",]),
      (["chinese":                "太湖边",
       "weizhi" :              "/d/guiyunzhuang/taihubian",]),
      (["chinese":                "少林寺般若堂九部",
       "weizhi" :              "/d/shaolin/banruo9",]),
      (["chinese":                "千佛庵大殿",
       "weizhi" :              "/d/emei/dadian",]),
      (["chinese":                "峨嵋厢房",
       "weizhi" :              "/d/emei/xfang1",]),
       (["chinese":                "洞中小道",
       "weizhi" :              "/d/dali/shifeng",]),

           });
