// qwlist1500.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 200,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "白色长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蝈蝈",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "草莓",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "柴",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "柴刀",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "钢刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "金蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "青蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "白色长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "羊鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "蛇胆粉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "竹篓",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蛇肉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
         ([      "quest":                HIY "三寸金莲" NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "兔肉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "白衣",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "粗磁大碗",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蛋糕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "果丹皮",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "沙田柚",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "安琪月饼",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "赏月糖果",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                GRN "蛇杖" NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            9,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "绣花针",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "粉红绸衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "绣花小鞋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "金戒指",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "狗皮",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            9,
                "pot_bonus":            6,
                "score" :               20
        ]),
        ([      "quest":                "红烧狗肉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "军服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "白布黑边袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "金项链",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "牢房钥匙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "衙役服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "竹棒",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "包子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "竹棒",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "大刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "铜号",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铜鼓",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "铜钹",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青葫芦",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            80,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "屠刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                YEL "腰带" NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "清心散",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            80,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蒙汗药",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            80,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蒙古布衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青色道袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "斗篷",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
         ([      "quest":                GRN"笛子"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            80,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "虎皮",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "清军服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "阿拉伯弯刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "戒刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            80,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "大剪刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "柳叶刀",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "哈密瓜",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "绿色长裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "馕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "冬不拉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            68,
                "pot_bonus":            48,
                "score" :               20
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黑衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "灰色长衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黄色长衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蓝绸衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "浅黄衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "浅碧衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "绿衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                BLK"烟斗"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "淡黄衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "菜刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黄色长衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黄布袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                MAG"麝香"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "铁棍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "烧红的铁锤",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIG"玄铁剑"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "长鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "湖州粽子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "琉璃茄子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "貂皮大氅",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "玄色长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "地牢钥匙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "紫花夹袄",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "绣花针",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                GRN"玉蜂针"NOR,
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "香茶",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "茶碗",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "竹剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIM"荔枝"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIY"龙眼"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            60,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                HIG"柰"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                HIC"铁铲"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            50,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "水靠",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            50,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                HIC"铁铲"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            50,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "维吾尔族长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "斗篷",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                YEL"黏糕"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "钥匙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "好逑汤",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黄色长衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                BLK"鬼头刀"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            160,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "绣花绷架",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "浅红衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIG"浅绿纱布"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIB"天蓝锦缎"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                HIM"粉红丝绸"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                RED"大红土布"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铁背心",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "长鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "长剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "钢杖",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "牡丹茶",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "配丹方",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                WHT"虎骨"NOR,
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "白骨",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIG"青苹果"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                HIM"桃子"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                HIY"月饼"NOR,
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                HIC"沙锅饭"NOR,
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                HIW"沙锅豆腐"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                HIR"沙锅丸子"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "金创药",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "五香花生",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铁锤",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "老白干",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "雄黄酒",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "金创药",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "齐眉棍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "白布黑边袈裟",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
         ([      "quest":                GRN"方天画戟"NOR,
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "熏田鸡",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铁手掌",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黄布袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "肥鸭",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                YEL"腰带"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "啃得精光的鸡腿骨头",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
          ([      "quest":                HIC"兰花扶穴手秘诀"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "金蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "水蜜桃",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蟒蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "毒蛇胆",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            14,
                "pot_bonus":            7,
                "score" :               20
        ]),
        ([      "quest":                "雄黄",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "银丝卷",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "拔丝山药",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "青色丝袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "黑色劲装",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "道德经",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "大乘涅磐经",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "『星宿毒经〖上册〗』",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "布袋" ,
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "玉佩",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "太极剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "破碗",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "天蚕衣",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "四书五经",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "虎符",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "紫霞袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "游龙剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            180,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "玉女剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "化缘钵",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "盟主令",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "带血的丝巾",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "骰子",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "断龙刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "锄头",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "烧饼",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "香茶",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "毒经",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "柴刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "蜡烛",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "玉石子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "菩提杖",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "香罗帕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "佩剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            140,
                "pot_bonus":            70,
                "score" :               20
        ]),
        ([      "quest":                "蒙汗药",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "硫磺",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "太极十三势",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "沙虫",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "沙虫壳",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "羊鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "长鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "波斯长袍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "冬不拉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "小毛驴",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "火折",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "哈密瓜",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "伊犁马",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "马奶酒壶",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "馕",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铜钹",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铜鼓",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铜号",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "阿拉伯弯刀",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "维吾尔族长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "天山雪莲",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "花雕酒袋",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "药锄",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "清心散",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "凌波微步图谱",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
          ([      "quest":                HIC"『少林拜师必读』"NOR,
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "铁棍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "面具",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "绿色长裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "金项链",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "粉红绸衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "雷震挡",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
