//存放三种类型的条件解释：poison-毒，disease-疾病，injure-创伤
nosave mapping cond_def=
(["anran_poison":
	(["name":"情毒",
		"type":"poison"]),
  "bee_poison":
	(["name":"蜂毒",
		"type":"poison"]),
  "bing_poison":
	(["name":"冰魄银针毒",
		"type":"poison"]),
  "bleeding":
	(["name":"流血",
		"type":"injure"]),
  "bt_poison":
	(["name":"白驼蛇毒",
		"type":"poison"]),
  "cake_drug":
	(["name":"腹泻",
		"type":"disease"]),
  "cannt_eq":
	(["name":"刺腕",
		"type":"injure"]),
  "chanchu_poison":
	(["name":"蟾蜍毒",
		"type":"poison"]),
  "chuanxin":
	(["name":"穿心钉",
		"type":"injure"]),
  "crazy":
	(["name":"发疯",
		"type":"disease"]),
  "drunk":
	(["name":"醉酒",
		"type":"disease"]),
  "dsy_poison":
	(["name":"密宗大手印",
		"type":"poison"]),
  "emerald_poison":
	(["name":"玄冰毒",
		"type":"poison"]),
  "fs_poison":
	(["name":"腐尸毒",
		"type":"poison"]),
  "heat":
	(["name":"燥热",
		"type":"disease"]),
  "hyd_condition":
	(["name":"火焰刀焚伤",
		"type":"injure"]),
  "ill_fashao":
	(["name":"发烧",
		"type":"disease"]),
  "ill_kesou":
	(["name":"咳嗽",
		"type":"disease"]),
  "ill_shanghan":
	(["name":"伤寒",
		"type":"disease"]),
  "ill_zhongshu":
	(["name":"中暑",
		"type":"disease"]),
  "insect_poison":
	(["name":"蜂毒",
		"type":"poison"]),
  "jiaofei-fire":
	(["name":"烈火烧伤",
		"type":"injure"]),
  "kuangre":
	(["name":"狂热",
		"type":"disease"]),
  "nx_zhua":
	(["name":"凝血神爪毒",
		"type":"poison"]),
  "qianzhu":
	(["name":"千蛛万毒",
		"type":"poison"]),
  "qishang":
	(["name":"七伤拳伤心脉",
		"type":"poison"]),
  "rose_poison":
	(["name":"火玫瑰毒",
		"type":"poison"]),
  "s-poison":
	(["name":"断肠散毒",
		"type":"poison"]),
  "san_poison":
	(["name":"断肠散毒",
		"type":"poison"]),
  "sanxiao_poison":
	(["name":"三笑逍遥散",
		"type":"poison"]),
  "scorpion_poison":
	(["name":"蝎毒",
		"type":"poison"]),
  "sha_poison":
	(["name":"铁砂掌毒",
		"type":"poison"]),
  "shuoxin":
	(["name":"烁心弹焚伤",
		"type":"injure"]),
  "slumber_drug":
	(["name":"蒙汗药",
		"type":"poison"]),
  "snake_poison":
	(["name":"蛇毒",
		"type":"poison"]),
  "ss_poison":
	(["name":"生死符",
		"type":"poison"]),
  "tangshang":
	(["name":"烫伤",
		"type":"injure"]),
  "unchblk" :
  (["name":"禁言",
		"type":"disease"]),
  "wannianzui":
	(["name":"万年醉",
		"type":"disease"]),
  "wenyi":
	(["name":"瘟疫",
		"type":"disease"]),
  "wudu_poison":
	(["name":"五毒伤害",
		"type":"poison"]),
  "wugong_poison":
	(["name":"蜈蚣毒",
		"type":"poison"]),
  "x_shihui":
	(["name":"石灰眼瞎",
		"type":"injure"]),	
  "xx_poison":
	(["name":"星宿毒掌毒",
		"type":"poison"]),
  "xxfog-poison":
	(["name":"星宿毒雾",
		"type":"poison"]),
  "xx-poison-palsy":
	(["name":"星宿麻痹",
		"type":"poison"]),
  "xx-poison-palsy2":
	(["name":"星宿麻痹",
		"type":"poison"]),
  "xxx_poison":
	(["name":"冰魄寒毒",
		"type":"poison"]),
  "yf_condition":
	(["name":"玉蜂针毒",
		"type":"poison"])]);
