mixed* npclist = ({
([ "name":"罗天傲",         "id":"luo tianao"      , "exp":500000]),
([ "name":"胡飞",         "id":"hu fei"      , "exp":2000000]),
([ "name":"欧阳血",         "id":"ouyang xue"      , "exp":10000000]),
([ "name":"孙笑痴",         "id":"sun xiaochi"      , "exp":5000000]),
([ "name":"陈爽",         "id":"chen shuang"      , "exp":500000]),
([ "name":"[1;31m鬼手[2;37;0m",         "id":"gui shou"      , "exp":8000000]),
([ "name":"毒蛇",         "id":"snake"      , "exp":1000]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1536]),
([ "name":"黑冠巨蟒",         "id":"snake"      , "exp":1000000]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1682]),
([ "name":"竹叶青蛇",         "id":"qing she"      , "exp":3232]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1525]),
([ "name":"竹叶青蛇",         "id":"qing she"      , "exp":3104]),
([ "name":"菜花蛇",         "id":"caihua she"      , "exp":130]),
([ "name":"老材",         "id":"lao cai"      , "exp":10000]),
([ "name":"门卫",         "id":"men wei"      , "exp":9338]),
([ "name":"欧阳锋",         "id":"ouyang feng"      , "exp":12000000]),
([ "name":"教头",         "id":"trainer"      , "exp":30000]),
([ "name":"白衣少女",         "id":"white lady"      , "exp":1000]),
([ "name":"欧阳克",         "id":"ouyang ke"      , "exp":500000]),
([ "name":"管家",         "id":"guan jia"      , "exp":20000]),
([ "name":"陪练童子",         "id":"tongzi"      , "exp":10000]),
([ "name":"蛇奴",         "id":"she nu"      , "exp":10000]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1611]),
([ "name":"蜜蜂",         "id":"bee"      , "exp":700]),
([ "name":"舞蛇人",         "id":"snaker"      , "exp":30000]),
([ "name":"门卫",         "id":"men wei"      , "exp":9390]),
([ "name":"小青",         "id":"xiao qing"      , "exp":60000]),
([ "name":"竹叶青蛇",         "id":"qing she"      , "exp":3125]),
([ "name":"吴之荣",         "id":"wu zhirong"      , "exp":5000]),
([ "name":"女管家",         "id":"guan jia"      , "exp":1070500]),
([ "name":"家丁",         "id":"jia ding"      , "exp":4000]),
([ "name":"厨师",         "id":"chu shi"      , "exp":7500]),
([ "name":"鳌拜",         "id":"ao bai"      , "exp":1000000]),
([ "name":"喇嘛",         "id":"lama"      , "exp":50000]),
([ "name":"钱老本",         "id":"qian laoben"      , "exp":50000]),
([ "name":"土匪",         "id":"tufei"      , "exp":10000]),
([ "name":"章老三",         "id":"zhang laosan"      , "exp":25000]),
([ "name":"弟子",         "id":"dizi"      , "exp":18101]),
([ "name":"弟子",         "id":"dizi"      , "exp":10833]),
([ "name":"弟子",         "id":"dizi"      , "exp":14681]),
([ "name":"弟子",         "id":"dizi"      , "exp":15886]),
([ "name":"[1;37m白熊[2;37;0m",         "id":"bai xiong"      , "exp":4800000]),
([ "name":"大白熊",         "id":"big bear"      , "exp":20000000]),
([ "name":"[1;33m落第秀才[2;37;0m",         "id":"xiu cai"      , "exp":2000]),
([ "name":"萧远山",         "id":"xiao yuanshan"      , "exp":1800000]),
([ "name":"阎世魁",         "id":"yan shikui"      , "exp":400000]),
([ "name":"忽伦二虎",         "id":"er hu"      , "exp":45000]),
([ "name":"忽伦大虎",         "id":"da hu"      , "exp":50000]),
([ "name":"忽伦四虎",         "id":"si hu"      , "exp":35000]),
([ "name":"忽伦三虎",         "id":"san hu"      , "exp":40000]),
([ "name":"万震山",         "id":"wan zhenshan"      , "exp":500000]),
([ "name":"僵尸",         "id":"flesh corpse"      , "exp":3950224]),
([ "name":"玉真子",         "id":"yuzhen zi"      , "exp":1100000]),
([ "name":"滕一雷",         "id":"teng yilei"      , "exp":400000]),
([ "name":"冯锡范",         "id":"feng xifan"      , "exp":8000000]),
([ "name":"阎基",         "id":"yan ji"      , "exp":500000]),
([ "name":"赛总管",         "id":"sai zongguan"      , "exp":900000]),
([ "name":"焦文期",         "id":"jiao wenqi"      , "exp":300000]),
([ "name":"哈合台",         "id":"ha hetai"      , "exp":300000]),
([ "name":"田归农",         "id":"tian guinong"      , "exp":700000]),
([ "name":"流氓",         "id":"liu mang"      , "exp":1000]),
([ "name":"流氓头",         "id":"liumang tou"      , "exp":7000]),
([ "name":"大狼狗",         "id":"wolf dog"      , "exp":1000]),
([ "name":"管家",         "id":"guan jia"      , "exp":7500]),
([ "name":"崔员外",         "id":"cui yuanwai"      , "exp":25000]),
([ "name":"空空儿",         "id":"kong kong"      , "exp":50000]),
([ "name":"龟奴",         "id":"gui nu"      , "exp":95000]),
([ "name":"钱眼开",         "id":"qian yankai"      , "exp":50000]),
([ "name":"地痞",         "id":"di pi"      , "exp":2000]),
([ "name":"王五",         "id":"wang wu"      , "exp":20000]),
([ "name":"百晓生",         "id":"bai xiaosheng"      , "exp":2500]),
([ "name":"歌女",         "id":"ge nu"      , "exp":3000]),
([ "name":"石匠",         "id":"shi jiang"      , "exp":5000]),
([ "name":"色楞",         "id":"se leng"      , "exp":5000]),
([ "name":"灵智上人",         "id":"lingzhi shangren"      , "exp":600000]),
([ "name":"旺仲",         "id":"hufa lama"      , "exp":119491]),
([ "name":"鸠摩智",         "id":"jiumo zhi"      , "exp":13000000]),
([ "name":"黑林钵夫",         "id":"heilin bofu"      , "exp":30000]),
([ "name":"呼拉干嘉",         "id":"hufa lama"      , "exp":100129]),
([ "name":"宗赞王子",         "id":"zongzan wangzi"      , "exp":300000]),
([ "name":"石拉",         "id":"tufan wushi"      , "exp":62168]),
([ "name":"二丑",         "id":"er chou"      , "exp":11500]),
([ "name":"五丑",         "id":"wu chou"      , "exp":10000]),
([ "name":"三丑",         "id":"san chou"      , "exp":11000]),
([ "name":"大丑",         "id":"da chou"      , "exp":12000]),
([ "name":"四丑",         "id":"si chou"      , "exp":10500]),
([ "name":"呼巴音",         "id":"hu bayin"      , "exp":200000]),
([ "name":"善勇",         "id":"shan yong"      , "exp":400000]),
([ "name":"胜谛",         "id":"sheng di"      , "exp":500000]),
([ "name":"哲罗星",         "id":"zheluo xing"      , "exp":350000]),
([ "name":"摩诃巴思",         "id":"mohe basi"      , "exp":100000]),
([ "name":"扎拉敦",         "id":"hufa lama"      , "exp":94392]),
([ "name":"宝象",         "id":"bao xiang"      , "exp":300000]),
([ "name":"仓洛尊贡",         "id":"hufa lama"      , "exp":117058]),
([ "name":"桑结",         "id":"sang jie"      , "exp":800000]),
([ "name":"血刀老祖",         "id":"xuedao laozu"      , "exp":1000000]),
([ "name":"[1;37m雪豹[2;37;0m",         "id":"xue bao"      , "exp":260000]),
([ "name":"波罗星",         "id":"boluo xing"      , "exp":250000]),
([ "name":"温卧儿",         "id":"wenwo er"      , "exp":70000]),
([ "name":"央拉",         "id":"jian gong"      , "exp":10000]),
([ "name":"倭寇",         "id":"wo kou"      , "exp":15000]),
([ "name":"东瀛浪人",         "id":"langren"      , "exp":18000]),
([ "name":"[1;33m山本五十六[2;37;0m",         "id":"wolf"      , "exp":500000]),
([ "name":"海蟹",         "id":"hai xie"      , "exp":20000]),
([ "name":"[1;36m东瀛武士[2;37;0m",         "id":"wu shi"      , "exp":40000]),
([ "name":"宋青书",         "id":"song qingshu"      , "exp":80000]),
([ "name":"野鬼",         "id":"ghost"      , "exp":20000]),
([ "name":"猴子",         "id":"monkey"      , "exp":10000]),
([ "name":"梅超风",         "id":"mei chaofeng"      , "exp":350000]),
([ "name":"陈玄风",         "id":"chen xuanfeng"      , "exp":400000]),
([ "name":"[30m黑鹰[2;37;0m",         "id":"hei ying"      , "exp":15000]),
([ "name":"[31m火蛇[2;37;0m",         "id":"snake"      , "exp":1000]),
([ "name":"[1;36m眼镜蛇[2;37;0m",         "id":"snake"      , "exp":1200]),
([ "name":"[32m竹青蛇[2;37;0m",         "id":"snake"      , "exp":1500]),
([ "name":"[31m巨莽[2;37;0m",         "id":"ju mang"      , "exp":100000]),
([ "name":"老虎",         "id":"lao hu"      , "exp":50000]),
([ "name":"小偷",         "id":"xiao tou"      , "exp":2300]),
([ "name":"[30m疯子[2;37;0m",         "id":"crazy man"      , "exp":50619]),
([ "name":"绿营清兵",         "id":"qing bing"      , "exp":20000]),
([ "name":"李可秀",         "id":"li kexiu"      , "exp":150000]),
([ "name":"李铁嘴",         "id":"fortune teller"      , "exp":2500]),
([ "name":"天山童姥",         "id":"tong lao"      , "exp":10000000]),
([ "name":"菊剑",         "id":"ju jian"      , "exp":500000]),
([ "name":"狼",         "id":"wolf"      , "exp":3000]),
([ "name":"店小二",         "id":"xiao er"      , "exp":100000]),
([ "name":"绿竹翁",         "id":"lvzhu weng"      , "exp":500000]),
([ "name":"黛绮丝",         "id":"dai qisi"      , "exp":500000]),
([ "name":"张无忌",         "id":"zhang wuji"      , "exp":12000000]),
([ "name":"[1;37m厚土旗众[2;37;0m",         "id":"qi zhong"      , "exp":1500]),
([ "name":"颜垣",         "id":"yan yuan"      , "exp":50000]),
([ "name":"[34m洪水旗众[2;37;0m",         "id":"qi zhong"      , "exp":4800]),
([ "name":"唐洋",         "id":"tang yang"      , "exp":58000]),
([ "name":"[33m巨木旗众[2;37;0m",         "id":"qi zhong"      , "exp":2500]),
([ "name":"闻苍松",         "id":"wen cangsong"      , "exp":55000]),
([ "name":"[33m烈火旗众[2;37;0m",         "id":"qi zhong"      , "exp":3800]),
([ "name":"辛然",         "id":"xin ran"      , "exp":55000]),
([ "name":"庄丁",         "id":"zhuang ding"      , "exp":30000]),
([ "name":"[33m锐金旗众[2;37;0m",         "id":"qi zhong"      , "exp":4000]),
([ "name":"庄铮",         "id":"zhuang zheng"      , "exp":58000]),
([ "name":"野狗",         "id":"dog"      , "exp":0]),
([ "name":"阿善",         "id":"a shan"      , "exp":25000]),
([ "name":"殷天正",         "id":"yin tianzheng"      , "exp":500000]),
([ "name":"韦一笑",         "id":"wei yixiao"      , "exp":400000]),
([ "name":"老顾",         "id":"lao gu"      , "exp":1000]),
([ "name":"老仆",         "id":"lao pu"      , "exp":1000]),
([ "name":"武师",         "id":"wushi"      , "exp":50000]),
([ "name":"教头",         "id":"jiao tou"      , "exp":20000]),
([ "name":"亲兵",         "id":"qin bing"      , "exp":72024]),
([ "name":"亲兵",         "id":"qin bing"      , "exp":73469]),
([ "name":"吴三桂",         "id":"wu sangui"      , "exp":3545439]),
([ "name":"护院武师",         "id":"hu yuan"      , "exp":639166]),
([ "name":"亲兵头",         "id":"qin bingtou"      , "exp":119463]),
([ "name":"亲兵",         "id":"qin bing"      , "exp":70203]),
([ "name":"萍水逢",         "id":"ping shui"      , "exp":200]),
([ "name":"小妾",         "id":"xiao qie"      , "exp":200]),
([ "name":"吴应雄",         "id":"wu yingxiong"      , "exp":80000]),
([ "name":"独孤梦",         "id":"dugu meng"      , "exp":0]),
([ "name":"杀手帮弟子",         "id":"dizi"      , "exp":2500]),
([ "name":"杀手帮女弟子",         "id":"nvdizi"      , "exp":2500]),
([ "name":"婆子",         "id":"pozi"      , "exp":500]),
([ "name":"黑熊",         "id":"bear"      , "exp":6000]),
([ "name":"豹子",         "id":"baozi"      , "exp":6000]),
([ "name":"狐狸",         "id":"huli"      , "exp":6000]),
([ "name":"罡风杀手",         "id":"feng"      , "exp":350000]),
([ "name":"霏云杀手",         "id":"yun"      , "exp":150000]),
([ "name":"擎雷杀手",         "id":"lei"      , "exp":250000]),
([ "name":"涟电杀手",         "id":"dian"      , "exp":450000]),
([ "name":"崆潮杀手",         "id":"chao"      , "exp":650000]),
([ "name":"浪回头",         "id":"lang huitou"      , "exp":500000]),
([ "name":"楚云飞",         "id":"chu yunfei"      , "exp":12772657]),
([ "name":"[31m赤练蛇[2;37;0m",         "id":"snake"      , "exp":600000]),
([ "name":"野狼",         "id":"wolf"      , "exp":800000]),
([ "name":"[31m蜈蚣[2;37;0m",         "id":"wu gong"      , "exp":500000]),
([ "name":"野猴",         "id":"monkey"      , "exp":400000]),
([ "name":"小土匪",         "id":"xiao tufei"      , "exp":1500000]),
([ "name":"虎头獒",         "id":"hutou ao"      , "exp":900000]),
([ "name":"吸血蝙蝠",         "id":"xixue bianfu"      , "exp":800000]),
([ "name":"狐狸",         "id":"fox"      , "exp":700000]),
([ "name":"野猪",         "id":"ye zhu"      , "exp":900000]),
([ "name":"酒神张",         "id":"jiushen zhang"      , "exp":100]),
([ "name":"沥泉怪蛇",         "id":"liquan guaishe"      , "exp":18000000]),
([ "name":"蜂王",         "id":"feng wang"      , "exp":1500]),
([ "name":"尹志平",         "id":"yin zhiping"      , "exp":50000]),
([ "name":"李莫愁",         "id":"li mochou"      , "exp":150000]),
([ "name":"怪人",         "id":"guai ren"      , "exp":18000000]),
([ "name":"上官云",         "id":"shangguan yun"      , "exp":500000]),
([ "name":"日月教众",         "id":"riyue jiaozhong"      , "exp":25000]),
([ "name":"[35m紫衫使者[2;37;0m",         "id":"zishan shizhe"      , "exp":150000]),
([ "name":"东方不败",         "id":"dongfang bubai"      , "exp":5000]),
([ "name":"杨莲亭",         "id":"yang lianting"      , "exp":5000]),
([ "name":"任我行",         "id":"ren woxing"      , "exp":11000000]),
([ "name":"东方不败",         "id":"dongfang bubai"      , "exp":15000000]),
([ "name":"丁坚",         "id":"ding jian"      , "exp":100000]),
([ "name":"向问天",         "id":"xiang wentian"      , "exp":800000]),
([ "name":"任我行",         "id":"ren woxing"      , "exp":2000000]),
([ "name":"黄钟公",         "id":"huangzhong gong"      , "exp":800000]),
([ "name":"黑白子",         "id":"heibai zi"      , "exp":400000]),
([ "name":"日月教众",         "id":"riyue jiaozhong"      , "exp":5000]),
([ "name":"童百熊",         "id":"tong baixiong"      , "exp":50000]),
([ "name":"秃笔翁",         "id":"tubi weng"      , "exp":300000]),
([ "name":"农夫",         "id":"nong fu"      , "exp":20000]),
([ "name":"贾布",         "id":"jia bu"      , "exp":500000]),
([ "name":"日月教众",         "id":"riyue jiaozhong"      , "exp":50000]),
([ "name":"任盈盈",         "id":"ren yingying"      , "exp":300000]),
([ "name":"鲍大楚",         "id":"bao dachu"      , "exp":50000]),
([ "name":"日月教众",         "id":"riyue jiaozhong"      , "exp":15000]),
([ "name":"老鼠",         "id":"lao shu"      , "exp":100]),
([ "name":"何师我",         "id":"he shiwo"      , "exp":0]),
([ "name":"[1;37m白衣[2;37;0m弟子",         "id":"baiyi dizi"      , "exp":85747]),
([ "name":"[37m黑衣[2;37;0m弟子",         "id":"heiyi dizi"      , "exp":92310]),
([ "name":"[1;36m青衣[2;37;0m弟子",         "id":"qingyi dizi"      , "exp":232806]),
([ "name":"[1;33m黄衣[2;37;0m弟子",         "id":"huangyi dizi"      , "exp":211560]),
([ "name":"[1;37m白衣[2;37;0m弟子",         "id":"baiyi dizi"      , "exp":89276]),
([ "name":"[1;31m红衣[2;37;0m弟子",         "id":"hongyi dizi"      , "exp":148029]),
([ "name":"[1;31m红衣[2;37;0m弟子",         "id":"hongyi dizi"      , "exp":156352]),
([ "name":"无根道长",         "id":"wugen daozhang"      , "exp":500000]),
([ "name":"紫蘭",         "id":"zi lan"      , "exp":10000]),
([ "name":"胖头陀",         "id":"pang toutuo"      , "exp":400000]),
([ "name":"瘦头陀",         "id":"shou toutuo"      , "exp":400000]),
([ "name":"[37m黑衣[2;37;0m弟子",         "id":"heiyi dizi"      , "exp":241251]),
([ "name":"张淡月",         "id":"zhang danyue"      , "exp":500000]),
([ "name":"殷锦",         "id":"yin jin"      , "exp":500000]),
([ "name":"[1;33m黄衣[2;37;0m弟子",         "id":"huangyi dizi"      , "exp":123640]),
([ "name":"游蛇",         "id":"you she"      , "exp":42697]),
([ "name":"[33m金环蛇[2;37;0m",         "id":"jinhuan she"      , "exp":19231]),
([ "name":"[1;33m蟒蛇[2;37;0m",         "id":"mang she"      , "exp":22973]),
([ "name":"[33m尖吻蝮蛇[2;37;0m",         "id":"jianwenfu she"      , "exp":20029]),
([ "name":"[37m黑衣[2;37;0m弟子",         "id":"heiyi dizi"      , "exp":139505]),
([ "name":"[1;36m青衣[2;37;0m弟子",         "id":"qingyi dizi"      , "exp":98122]),
([ "name":"[1;33m黄衣[2;37;0m弟子",         "id":"huangyi dizi"      , "exp":275823]),
([ "name":"[1;31m红衣[2;37;0m弟子",         "id":"hongyi dizi"      , "exp":132111]),
([ "name":"[1;37m白衣[2;37;0m弟子",         "id":"baiyi dizi"      , "exp":120116]),
([ "name":"洪安通",         "id":"hong antong"      , "exp":15000000]),
([ "name":"苏荃",         "id":"su quan"      , "exp":10000000]),
([ "name":"[1;36m青衣[2;37;0m弟子",         "id":"qingyi dizi"      , "exp":141277]),
([ "name":"许雪亭",         "id":"xu xueting"      , "exp":500000]),
([ "name":"游蛇",         "id":"you she"      , "exp":50264]),
([ "name":"[33m金环蛇[2;37;0m",         "id":"jinhuan she"      , "exp":17204]),
([ "name":"[37m银环蛇[2;37;0m",         "id":"yinhuan she"      , "exp":11640]),
([ "name":"[36m眼镜蛇[2;37;0m",         "id":"yanjing she"      , "exp":45162]),
([ "name":"[33m金环蛇[2;37;0m",         "id":"jinhuan she"      , "exp":45175]),
([ "name":"[33m尖吻蝮蛇[2;37;0m",         "id":"jianwenfu she"      , "exp":36220]),
([ "name":"[36m眼镜蛇[2;37;0m",         "id":"yanjing she"      , "exp":45227]),
([ "name":"[33m金环蛇[2;37;0m",         "id":"jinhuan she"      , "exp":38159]),
([ "name":"[1;36m锦蛇[2;37;0m",         "id":"jin she"      , "exp":32627]),
([ "name":"[37m银环蛇[2;37;0m",         "id":"yinhuan she"      , "exp":24991]),
([ "name":"[36m眼镜蛇[2;37;0m",         "id":"yanjing she"      , "exp":30954]),
([ "name":"游蛇",         "id":"you she"      , "exp":11614]),
([ "name":"[33m金环蛇[2;37;0m",         "id":"jinhuan she"      , "exp":47353]),
([ "name":"[1;33m蟒蛇[2;37;0m",         "id":"mang she"      , "exp":28131]),
([ "name":"[1;36m锦蛇[2;37;0m",         "id":"jin she"      , "exp":43608]),
([ "name":"陆高轩",         "id":"lu gaoxuan"      , "exp":300000]),
([ "name":"[33m金环蛇[2;37;0m",         "id":"jinhuan she"      , "exp":34000]),
([ "name":"[36m眼镜蛇[2;37;0m",         "id":"yanjing she"      , "exp":24350]),
([ "name":"[37m银环蛇[2;37;0m",         "id":"yinhuan she"      , "exp":30560]),
([ "name":"[37m银环蛇[2;37;0m",         "id":"yinhuan she"      , "exp":28743]),
([ "name":"[1;36m锦蛇[2;37;0m",         "id":"jin she"      , "exp":21412]),
([ "name":"[33m尖吻蝮蛇[2;37;0m",         "id":"jianwenfu she"      , "exp":35796]),
([ "name":"[36m眼镜蛇[2;37;0m",         "id":"yanjing she"      , "exp":26878]),
([ "name":"[33m尖吻蝮蛇[2;37;0m",         "id":"jianwenfu she"      , "exp":52968]),
([ "name":"剑客",         "id":"jian ke"      , "exp":20000]),
([ "name":"公子哥",         "id":"gongzi"      , "exp":30056]),
([ "name":"刀客",         "id":"dao ke"      , "exp":15000]),
([ "name":"海公公",         "id":"hai gonggong"      , "exp":5000000]),
([ "name":"[32m竹叶青蛇[2;37;0m",         "id":"qing she"      , "exp":3054]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1650]),
([ "name":"[32m竹叶青蛇[2;37;0m",         "id":"qing she"      , "exp":3296]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1618]),
([ "name":"[32m竹叶青蛇[2;37;0m",         "id":"qing she"      , "exp":3028]),
([ "name":"金环蛇",         "id":"jin she"      , "exp":1660]),
([ "name":"地痞",         "id":"dipi"      , "exp":750]),
([ "name":"小流氓",         "id":"punk"      , "exp":500]),
([ "name":"翠花",         "id":"cui hua"      , "exp":200]),
([ "name":"李四",         "id":"li si"      , "exp":50000]),
([ "name":"王小二",         "id":"wang xiaoer"      , "exp":5000]),
([ "name":"猴子",         "id":"monkey"      , "exp":5000]),
([ "name":"土匪",         "id":"tufei"      , "exp":5000]),
([ "name":"小喽罗",         "id":"xiao louluo"      , "exp":500]),
([ "name":"小土匪",         "id":"xiao tufei"      , "exp":750]),
([ "name":"张三",         "id":"zhang san"      , "exp":200000]),
([ "name":"土匪头",         "id":"tufei tou"      , "exp":20000]),
([ "name":"小猴",         "id":"little monkey"      , "exp":50]),
([ "name":"菜花蛇",         "id":"snake"      , "exp":1000]),
([ "name":"[1;31m火麒麟[2;37;0m",         "id":"fire kylin"      , "exp":3000000]),
([ "name":"木剑封",         "id":"mu jianfeng"      , "exp":5000000]),
([ "name":"[37m老虎[2;37;0m",         "id":"tiger"      , "exp":50000]),
([ "name":"[30m土匪[2;37;0m",         "id":"tu fei"      , "exp":20000]),
([ "name":"[31m土匪[2;37;0m",         "id":"tu fei"      , "exp":20000]),
([ "name":"[31m土匪[2;37;0m",         "id":"tu fei"      , "exp":200000]),
([ "name":"达尔巴",         "id":"daer ba"      , "exp":650000]),
([ "name":"金轮法王",         "id":"jinlun fawang"      , "exp":15000000]),
([ "name":"尼摩星",         "id":"nimo xing"      , "exp":450000]),
([ "name":"[31m土匪头[2;37;0m",         "id":"tufei tou"      , "exp":50000]),
([ "name":"[30m黑熊[2;37;0m",         "id":"hei xiong"      , "exp":200000]),
([ "name":"郭没",         "id":"guo mo"      , "exp":25000]),
([ "name":"李秋水",         "id":"li qiushui"      , "exp":11000000]),
([ "name":"打手",         "id":"da shou"      , "exp":10502]),
([ "name":"黑老板",         "id":"hei laoban"      , "exp":80343]),
([ "name":"巴依",         "id":"bayi"      , "exp":25000]),
([ "name":"丁春秋",         "id":"ding chunqiu"      , "exp":1500000]),
([ "name":"星宿派号手",         "id":"haoshou"      , "exp":3000]),
([ "name":"狮吼子",         "id":"shihou zi"      , "exp":200000]),
([ "name":"星宿派鼓手",         "id":"gushou"      , "exp":4000]),
([ "name":"星宿派钹手",         "id":"boshou"      , "exp":2000]),
([ "name":"天狼子",         "id":"tianlang zi"      , "exp":150000]),
([ "name":"摘星子",         "id":"zhaixing zi"      , "exp":300000]),
([ "name":"采花子",         "id":"caihua zi"      , "exp":25000]),
([ "name":"秦伟邦",         "id":"qin weibang"      , "exp":600000]),
([ "name":"阿紫",         "id":"a zi"      , "exp":50000]),
([ "name":"出尘子",         "id":"chuchen zi"      , "exp":100000]),
([ "name":"[1;31m黄毛鬼[2;37;0m",         "id":"huangmao gui"      , "exp":100000]),
([ "name":"[1;31m秦桧[2;37;0m",         "id":"qin hui"      , "exp":0]),
([ "name":"包打听",         "id":"bao dating"      , "exp":500000]),
([ "name":"[1;36m盗墓高手[2;37;0m",         "id":"daomu gaoshou"      , "exp":7425969]),
([ "name":"[1;36m大内高手[2;37;0m",         "id":"danei gaoshou"      , "exp":5000000]),
});