mixed* npclist = ({
([ "name":"农家妇女",         "id":"woman"      , "exp":1200]),
([ "name":"丫环",         "id":"ya huan"      , "exp":300]),
([ "name":"张二楞",         "id":"zhang tiejiang"      , "exp":500]),
([ "name":"毫毛",         "id":"hao mao"      , "exp":100000000]),
([ "name":"小孩",         "id":"kid"      , "exp":50]),
([ "name":"店小二",         "id":"xiao er"      , "exp":100]),
([ "name":"樵夫",         "id":"qiao fu"      , "exp":800]),
([ "name":"白兔",         "id":"bai tu"      , "exp":200]),
([ "name":"麻雀",         "id":"maque"      , "exp":0]),
([ "name":"白鹤",         "id":"bai he"      , "exp":800000]),
([ "name":"花匠",         "id":"gardener"      , "exp":10000]),
([ "name":"农民",         "id":"man"      , "exp":2000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":65429]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":262192]),
([ "name":"官兵",         "id":"guan bing"      , "exp":35239]),
([ "name":"庄允城",         "id":"zhuang yuncheng"      , "exp":0]),
([ "name":"钱庄伙计",         "id":"huo ji"      , "exp":5000]),
([ "name":"梅老板",         "id":"mei laoban"      , "exp":600]),
([ "name":"官兵",         "id":"guan bing"      , "exp":68882]),
([ "name":"王武通",         "id":"wang wutong"      , "exp":200000]),
([ "name":"侍卫",         "id":"shi wei"      , "exp":5000]),
([ "name":"兵部侍郎",         "id":"bingbu shilang"      , "exp":22798]),
([ "name":"明珠",         "id":"ming zhu"      , "exp":20000]),
([ "name":"关安基",         "id":"guan anji"      , "exp":500000]),
([ "name":"伙计",         "id":"huoji"      , "exp":5000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":26198]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":167189]),
([ "name":"官兵",         "id":"guan bing"      , "exp":54537]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":157176]),
([ "name":"张氏",         "id":"zhang shi"      , "exp":30000]),
([ "name":"酸秀才",         "id":"suan xiucai"      , "exp":8000]),
([ "name":"茶博士",         "id":"cha boshi"      , "exp":1000]),
([ "name":"当铺伙计",         "id":"huo ji"      , "exp":80000]),
([ "name":"韦小宝",         "id":"wei xiaobao"      , "exp":50000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":30083]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":150077]),
([ "name":"官兵",         "id":"guan bing"      , "exp":38525]),
([ "name":"官兵",         "id":"guan bing"      , "exp":63067]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":287234]),
([ "name":"官兵",         "id":"guan bing"      , "exp":49125]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":509248]),
([ "name":"签客",         "id":"qian  ke"      , "exp":5000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":28914]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":522798]),
([ "name":"官兵",         "id":"guan bing"      , "exp":37981]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":549701]),
([ "name":"官兵",         "id":"guan bing"      , "exp":28406]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":341502]),
([ "name":"官兵",         "id":"guan bing"      , "exp":46377]),
([ "name":"独臂神尼",         "id":"dubi shenni"      , "exp":200000]),
([ "name":"掌柜",         "id":"zhang gui"      , "exp":7500]),
([ "name":"客店伙计",         "id":"kedian huoji"      , "exp":2500]),
([ "name":"麻将馆小姐",         "id":"girl"      , "exp":0]),
([ "name":"小贩",         "id":"seller"      , "exp":300]),
([ "name":"店小二",         "id":"xiao er"      , "exp":20000]),
([ "name":"吴六奇",         "id":"wu liuqi"      , "exp":1500000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":607]),
([ "name":"女赌客",         "id":"du ke"      , "exp":40000]),
([ "name":"多隆",         "id":"duo long"      , "exp":1000000]),
([ "name":"赛西施",         "id":"sai xishi"      , "exp":10000]),
([ "name":"侍卫教头",         "id":"shiwei jiaotou"      , "exp":300000]),
([ "name":"船夫",         "id":"chuan fu"      , "exp":57749]),
([ "name":"徐天川",         "id":"xu tianchuan"      , "exp":750000]),
([ "name":"磨刀匠",         "id":"modao jiang"      , "exp":3000]),
([ "name":"屠宰场伙计",         "id":"huo ji"      , "exp":10000]),
([ "name":"李力世",         "id":"li lishi"      , "exp":85000]),
([ "name":"镖头",         "id":"biao tou"      , "exp":5000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":41922]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":266940]),
([ "name":"官兵",         "id":"guan bing"      , "exp":58794]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":548185]),
([ "name":"官兵",         "id":"guan bing"      , "exp":49524]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":552956]),
([ "name":"张德福",         "id":"zhang defu"      , "exp":8000]),
([ "name":"喜来乐",         "id":"xi laile"      , "exp":10000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":24611]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":419080]),
([ "name":"官兵",         "id":"guan bing"      , "exp":32440]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":171684]),
([ "name":"官兵",         "id":"guan bing"      , "exp":66988]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":290594]),
([ "name":"游方和尚",         "id":"seng ren"      , "exp":10000]),
([ "name":"庄夫人",         "id":"san furen"      , "exp":100000]),
([ "name":"双儿",         "id":"shuang er"      , "exp":169163]),
([ "name":"官兵",         "id":"guan bing"      , "exp":64808]),
([ "name":"巡城武将",         "id":"wu jiang"      , "exp":158420]),
([ "name":"[1;35m殷素素[2;37;0m",         "id":"yin susu"      , "exp":4000000]),
([ "name":"谢无忌",         "id":"xie wuji"      , "exp":10000]),
([ "name":"张翠山",         "id":"zhang cuishan"      , "exp":5000000]),
([ "name":"[1;37m小鹿[2;37;0m",         "id":"xiao lu"      , "exp":900000]),
([ "name":"[1;33m谢逊[2;37;0m",         "id":"xie xun"      , "exp":90000000]),
([ "name":"狄云",         "id":"di yun"      , "exp":890000]),
([ "name":"皮货商",         "id":"pihuo shang"      , "exp":3000]),
([ "name":"店小二",         "id":"xiao er"      , "exp":1000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":51001]),
([ "name":"官兵",         "id":"guan bing"      , "exp":63191]),
([ "name":"武将",         "id":"wu jiang"      , "exp":75000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":52257]),
([ "name":"官兵",         "id":"guan bing"      , "exp":47406]),
([ "name":"赫尔苏",         "id":"he ersu"      , "exp":10000]),
([ "name":"[1;37m雪山隐者[2;37;0m",         "id":"yin zhe"      , "exp":200000]),
([ "name":"胡斐",         "id":"hu fei"      , "exp":8900000]),
([ "name":"酒馆老板",         "id":"lao ban"      , "exp":3000]),
([ "name":"行者",         "id":"xingzhe"      , "exp":20000]),
([ "name":"官兵",         "id":"guan bing"      , "exp":10000]),
([ "name":"林平之",         "id":"lin pingzhi"      , "exp":10000]),
([ "name":"史青山",         "id":"shi qingshan"      , "exp":200000]),
([ "name":"慕容复",         "id":"murong fu"      , "exp":2000000]),
([ "name":"阿庆嫂",         "id":"aqing sao"      , "exp":500]),
([ "name":"王铁匠",         "id":"wang tiejiang"      , "exp":1000]),
([ "name":"铁匠铺伙计",         "id":"huo ji"      , "exp":250]),
([ "name":"张帐房",         "id":"zhang zhangfang"      , "exp":2000]),
([ "name":"红娘",         "id":"hong niang"      , "exp":3000]),
([ "name":"推销小姐",         "id":"girl"      , "exp":400000]),
([ "name":"飞龙帮众",         "id":"bang zhong"      , "exp":5000]),
([ "name":"简长老",         "id":"jian zhanglao"      , "exp":1200000]),
([ "name":"洪七公",         "id":"hong qigong"      , "exp":11000000]),
([ "name":"赵狗儿",         "id":"zhao gouer"      , "exp":5000]),
([ "name":"田伯光",         "id":"tian boguang"      , "exp":150000]),
([ "name":"家丁",         "id":"jia ding"      , "exp":4000]),
([ "name":"沈千盅",         "id":"shen qianzhong"      , "exp":50000]),
([ "name":"韦春芳",         "id":"wei chunfang"      , "exp":25000]),
([ "name":"托钵僧",         "id":"tuobo seng"      , "exp":10000]),
([ "name":"程玉环",         "id":"cheng yuhuan"      , "exp":50000]),
([ "name":"殷老板",         "id":"yin laoban"      , "exp":50000]),
([ "name":"彭有敬",         "id":"peng youjing"      , "exp":1200000]),
([ "name":"鲁有脚",         "id":"lu youjiao"      , "exp":1200000]),
([ "name":"刘老板",         "id":"liu laoban"      , "exp":90000]),
([ "name":"绿萼",         "id":"lver"      , "exp":10493]),
([ "name":"龙华天",         "id":"long huatian"      , "exp":2000000]),
([ "name":"朱熹",         "id":"zhu xi"      , "exp":400000]),
([ "name":"虫子",         "id":"chong zi"      , "exp":800000000]),
([ "name":"胡金科",         "id":"hu jinke"      , "exp":60000]),
([ "name":"谢一绝",         "id":"xie yijue"      , "exp":50000]),
([ "name":"崔莺莺",         "id":"cui yingying"      , "exp":20000]),
([ "name":"衙役",         "id":"ya yi"      , "exp":7500]),
([ "name":"药铺伙计",         "id":"yaopu huoji"      , "exp":250]),
([ "name":"平一指",         "id":"ping yizhi"      , "exp":500000]),
([ "name":"陈震骐",         "id":"chen zhenqi"      , "exp":10000]),
([ "name":"谭友纪",         "id":"tan youji"      , "exp":30000]),
([ "name":"程药发",         "id":"cheng yaofa"      , "exp":30000]),
([ "name":"[1;37m小宝贝[2;37;0m",         "id":"bao bei"      , "exp":1000000]),
([ "name":"杨永福",         "id":"yang yongfu"      , "exp":40000]),
([ "name":"林震南",         "id":"lin zhennan"      , "exp":30000]),
([ "name":"冼老板",         "id":"xian laoban"      , "exp":50000]),
([ "name":"[1;31m醉汉[2;37;0m",         "id":"zui han"      , "exp":50000]),
([ "name":"宋老板",         "id":"song laoban"      , "exp":60000]),
([ "name":"士兵",         "id":"shi bing"      , "exp":50000]),
([ "name":"黄衣卫士",         "id":"wei shi"      , "exp":80000]),
([ "name":"摆夷老叟",         "id":"oldman"      , "exp":800]),
([ "name":"南国姑娘",         "id":"girl"      , "exp":1000]),
([ "name":"薛老板",         "id":"xue laoban"      , "exp":20000]),
([ "name":"何红药",         "id":"he hongyao"      , "exp":40000]),
([ "name":"江湖艺人",         "id":"jianghu yiren"      , "exp":4927]),
([ "name":"副将",         "id":"fu jiang"      , "exp":300000]),
([ "name":"傅思归",         "id":"fu sigui"      , "exp":500000]),
([ "name":"段陉",         "id":"duan jin"      , "exp":30000]),
([ "name":"摆夷判官",         "id":"pan guan"      , "exp":82598]),
([ "name":"总管",         "id":"zong guan"      , "exp":120000]),
([ "name":"护院武士",         "id":"wei shi"      , "exp":120000]),
([ "name":"小厮子",         "id":"xiao si"      , "exp":2230]),
([ "name":"古笃诚",         "id":"gu ducheng"      , "exp":500000]),
([ "name":"花匠",         "id":"hua jiang"      , "exp":3000]),
([ "name":"摆夷女子",         "id":"girl"      , "exp":3000]),
([ "name":"游客",         "id":"you ke"      , "exp":8000]),
([ "name":"巴天石",         "id":"ba tianshi"      , "exp":700000]),
([ "name":"范骅",         "id":"fan ye"      , "exp":800000]),
([ "name":"华赫艮",         "id":"hua hegen"      , "exp":700000]),
([ "name":"侍从",         "id":"shi cong"      , "exp":1544]),
([ "name":"大土司",         "id":"da tusi"      , "exp":8000]),
([ "name":"侍从",         "id":"shi cong"      , "exp":1391]),
([ "name":"族头人",         "id":"zu touren"      , "exp":6000]),
([ "name":"褚万里",         "id":"zhu wanli"      , "exp":500000]),
([ "name":"锦衣卫士",         "id":"wei shi"      , "exp":60000]),
([ "name":"朱丹臣",         "id":"zhu danchen"      , "exp":500000]),
([ "name":"卫士长",         "id":"weishi zhang"      , "exp":5000]),
([ "name":"小厮子",         "id":"xiao si"      , "exp":2247]),
([ "name":"崔百泉",         "id":"cui baiquan"      , "exp":300000]),
([ "name":"护院武士领队",         "id":"weishi lingdui"      , "exp":300000]),
([ "name":"段正淳",         "id":"duan zhengchun"      , "exp":3000000]),
([ "name":"小丫鬟",         "id":"ya huan"      , "exp":2000]),
([ "name":"素衣卫士",         "id":"wei shi"      , "exp":120000]),
([ "name":"侍者",         "id":"shi zhe"      , "exp":4500]),
([ "name":"高升泰",         "id":"gao shengtai"      , "exp":500000]),
([ "name":"陪从",         "id":"pei cong"      , "exp":4000]),
([ "name":"傣族首领",         "id":"daizu shouling"      , "exp":50000]),
([ "name":"刀白凤",         "id":"dao baifeng"      , "exp":3000000]),
([ "name":"小道姑",         "id":"xiao daogu"      , "exp":2278]),
([ "name":"丹宗扎饶",         "id":"zayi lama"      , "exp":10896]),
([ "name":"藏族牧民",         "id":"zangzu mumin"      , "exp":4089]),
([ "name":"李招财",         "id":"li zhaocai"      , "exp":100]),
([ "name":"岗绛丹",         "id":"jinxiang ke"      , "exp":1885]),
([ "name":"哲布尊巴丹",         "id":"huofo"      , "exp":5000000]),
([ "name":"卡宗亲",         "id":"zayi lama"      , "exp":3382]),
([ "name":"藏獒",         "id":"zang ao"      , "exp":300000]),
([ "name":"牦牛",         "id":"mao niu"      , "exp":50000]),
([ "name":"藏族妇女",         "id":"zangzu funv"      , "exp":500]),
([ "name":"裂腹鱼",         "id":"liefu yu"      , "exp":3000]),
([ "name":"支麻鸭",         "id":"zhima ya"      , "exp":2000]),
([ "name":"斑头雁",         "id":"bantou yan"      , "exp":5000]),
([ "name":"王三力",         "id":"wang sanli"      , "exp":20000]),
([ "name":"胡贵",         "id":"hu gui"      , "exp":2000]),
([ "name":"夹第敦图",         "id":"zayi lama"      , "exp":8211]),
([ "name":"肖老头",         "id":"xiao laotou"      , "exp":2300]),
([ "name":"妇女",         "id":"woman"      , "exp":300]),
([ "name":"仓呼",         "id":"du ke"      , "exp":1000]),
([ "name":"亲松业",         "id":"worker"      , "exp":140]),
([ "name":"白无常",         "id":"white gargoyle"      , "exp":20000]),
([ "name":"黑无常",         "id":"black gargoyle"      , "exp":20000]),
([ "name":"[32m渔家少女[2;37;0m",         "id":"shao nv"      , "exp":800]),
([ "name":"老船家",         "id":"chuan jia"      , "exp":1000]),
([ "name":"史婆婆",         "id":"shi"      , "exp":75000]),
([ "name":"白阿绣",         "id":"bai axiu"      , "exp":103017]),
([ "name":"海鸟",         "id":"hai niao"      , "exp":800]),
([ "name":"老渔夫",         "id":"yu fu"      , "exp":500]),
([ "name":"静慧师太",         "id":"jinghui shitai"      , "exp":150000]),
([ "name":"文善师太",         "id":"wenshan shitai"      , "exp":10000]),
([ "name":"文闲师太",         "id":"wenxian shitai"      , "exp":10000]),
([ "name":"文怡师太",         "id":"wenyi shitai"      , "exp":10000]),
([ "name":"静闲师太",         "id":"jingxian shitai"      , "exp":150000]),
([ "name":"静空师太",         "id":"jingkong shitai"      , "exp":150000]),
([ "name":"静真师太",         "id":"jingzhen shitai"      , "exp":150000]),
([ "name":"静虚师太",         "id":"jingxu shitai"      , "exp":150000]),
([ "name":"静迦师太",         "id":"jingjia shitai"      , "exp":150000]),
([ "name":"静玄师太",         "id":"jingxuan shitai"      , "exp":150000]),
([ "name":"静照师太",         "id":"jingzhao shitai"      , "exp":150000]),
([ "name":"文凌师太",         "id":"wenling shitai"      , "exp":10000]),
([ "name":"静道师太",         "id":"jingdao shitai"      , "exp":150000]),
([ "name":"静风师太",         "id":"jingfeng shitai"      , "exp":150000]),
([ "name":"静心师太",         "id":"jingxin shitai"      , "exp":150000]),
([ "name":"静和师太",         "id":"jinghe shitai"      , "exp":150000]),
([ "name":"白猿",         "id":"baiyuan"      , "exp":10000]),
([ "name":"小女孩",         "id":"little girl"      , "exp":50]),
([ "name":"小贩",         "id":"xiao fan"      , "exp":250]),
([ "name":"尼姑",         "id":"nigu"      , "exp":2000]),
([ "name":"小尼姑",         "id":"xiao nigu"      , "exp":100]),
([ "name":"文虚师太",         "id":"wenxu shitai"      , "exp":10000]),
([ "name":"守山弟子",         "id":"shoushan dizi"      , "exp":10000]),
([ "name":"巡山弟子",         "id":"xunshan dizi"      , "exp":20000]),
([ "name":"文月师太",         "id":"wenyue shitai"      , "exp":10000]),
([ "name":"文心师太",         "id":"wenxin shitai"      , "exp":10000]),
([ "name":"女孩",         "id":"girl"      , "exp":80]),
([ "name":"尼姑",         "id":"nigu"      , "exp":800]),
([ "name":"贝锦仪",         "id":"bei jinyi"      , "exp":150000]),
([ "name":"赵灵珠",         "id":"zhao lingzhu"      , "exp":150000]),
([ "name":"李明霞",         "id":"li mingxia"      , "exp":150000]),
([ "name":"苏梦清",         "id":"su mengqing"      , "exp":150000]),
([ "name":"黎生",         "id":"li sheng"      , "exp":800000]),

([ "name":"左全",         "id":"zuo quan"      , "exp":408000]),
([ "name":"裘万家",         "id":"qiu wanjia"      , "exp":10000]),
([ "name":"江上游",         "id":"jiang shangyou"      , "exp":80000]),
([ "name":"何不净",         "id":"he bujing"      , "exp":400000]),
([ "name":"梁长老",         "id":"liang zhanglao"      , "exp":1200000]),
([ "name":"李斧头",         "id":"li futou"      , "exp":200000]),
([ "name":"莫不收",         "id":"mo bushou"      , "exp":20000]),
([ "name":"马俱为",         "id":"ma juwei"      , "exp":509000]),
([ "name":"余洪兴",         "id":"yu hongxing"      , "exp":820000]),
([ "name":"快活三",         "id":"kuaihuo san"      , "exp":53000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":311]),
([ "name":"小贩",         "id":"xiao fan"      , "exp":300]),
([ "name":"野兔",         "id":"ye tu"      , "exp":500]),
([ "name":"老农",         "id":"lao nong"      , "exp":307]),
([ "name":"民女",         "id":"min nv"      , "exp":455]),
([ "name":"砍柴人",         "id":"kanchai ren"      , "exp":10000]),
([ "name":"炼丹人",         "id":"liandan ren"      , "exp":10000]),
//([ "name":"陆乘风",         "id":"lu chengfeng"      , "exp":400000]),
([ "name":"归云庄卫士",         "id":"wei shi"      , "exp":10000]),
([ "name":"[34m归云庄[2;37;0m[31m武士[2;37;0m",         "id":"wu shi"      , "exp":84280]),
([ "name":"水老板",         "id":"shui laoban"      , "exp":8000]),
([ "name":"陆冠英",         "id":"lu guanying"      , "exp":60000]),
([ "name":"陈叁",         "id":"chen san"      , "exp":10000]),
([ "name":"王德",         "id":"wang de"      , "exp":11000]),
([ "name":"阿香",         "id":"a xiang"      , "exp":3000]),
([ "name":"庄仆",         "id":"zhuang pu"      , "exp":1000]),
([ "name":"阿牧",         "id":"a mu"      , "exp":3000]),
([ "name":"练功弟子",         "id":"liangong dizi"      , "exp":2254]),
([ "name":"[1;36m御马翁[2;37;0m",         "id":"yu maweng"      , "exp":2000]),
([ "name":"曲灵风",         "id":"quling feng"      , "exp":500000]),
([ "name":"神灵",         "id":"shen ling"      , "exp":500000]),
([ "name":"白骨架",         "id":"gu jia"      , "exp":50000]),
([ "name":"老妇人",         "id":"oldwoman"      , "exp":27846]),
([ "name":"王铁",         "id":"wang tie"      , "exp":100185]),
([ "name":"[1;36m猎户[2;37;0m",         "id":"lie hu"      , "exp":16909]),
([ "name":"游客",         "id":"youke"      , "exp":750]),
([ "name":"小二",         "id":"xiao er"      , "exp":100]),
([ "name":"屠夫",         "id":"tu fu"      , "exp":3000]),
([ "name":"卖艺人",         "id":"maiyi ren"      , "exp":20000]),
([ "name":"卖艺人",         "id":"maiyi ren"      , "exp":18000]),
([ "name":"商人",         "id":"shang ren"      , "exp":1000]),
([ "name":"[1;36m算卦先生[2;37;0m",         "id":"suangua xiansheng"      , "exp":200000]),
([ "name":"小花",         "id":"xiao hua"      , "exp":4000]),
([ "name":"隐者",         "id":"yin zhe"      , "exp":100000]),
([ "name":"庄童",         "id":"zhuang tong"      , "exp":50]),
([ "name":"总管",         "id":"zong guan"      , "exp":20000]),
([ "name":"杨女",         "id":"yang nu"      , "exp":1500000]),
([ "name":"孙婆婆",         "id":"sun popo"      , "exp":150000]),
([ "name":"杨过",         "id":"yang guo"      , "exp":11000000]),
([ "name":"小龙女",         "id":"xiao longnu"      , "exp":10000000]),
([ "name":"扬冰儿",         "id":"yang binger"      , "exp":500000]),
([ "name":"扬雪儿",         "id":"yang xuer"      , "exp":500000]),
([ "name":"女孩",         "id":"girl"      , "exp":500]),
([ "name":"小虹",         "id":"xiao hong"      , "exp":50000]),
([ "name":"执箫少女",         "id":"xiao"      , "exp":5000]),
([ "name":"女孩",         "id":"girl"      , "exp":70]),
([ "name":"抚琴少女",         "id":"qin"      , "exp":5000]),
([ "name":"小玲",         "id":"xiao ling"      , "exp":50000]),
([ "name":"陆无双",         "id":"lu wushuang"      , "exp":50000]),
([ "name":"马三",         "id":"ma san"      , "exp":500000]),
([ "name":"家丁",         "id":"jia ding"      , "exp":30000]),
([ "name":"裴老板",         "id":"pei"      , "exp":50000]),
([ "name":"胖嫂",         "id":"pang sao"      , "exp":50000]),
([ "name":"酒客",         "id":"jiu ke"      , "exp":20000]),
([ "name":"红花会众",         "id":"honghua huizhong"      , "exp":20000]),
([ "name":"章进",         "id":"zhang jin"      , "exp":120000]),
([ "name":"石双英",         "id":"shi shuangying"      , "exp":200000]),
([ "name":"常赫志",         "id":"chang hezhi"      , "exp":5000000]),
([ "name":"常伯志",         "id":"chang bozhi"      , "exp":5000000]),
([ "name":"心砚",         "id":"xin yan"      , "exp":100000]),
([ "name":"陈家洛",         "id":"chen jialuo"      , "exp":20000000]),
([ "name":"蒋四根",         "id":"jiang sigen"      , "exp":150000]),
([ "name":"余鱼同",         "id":"yu yutong"      , "exp":1000000]),
([ "name":"赵半山",         "id":"zhao banshan"      , "exp":20000000]),
([ "name":"骆冰",         "id":"luo bing"      , "exp":15000000]),
([ "name":"无尘道长",         "id":"wuchen daozhang"      , "exp":20000000]),
([ "name":"徐天宏",         "id":"xu tianhong"      , "exp":3500000]),
([ "name":"卫春华",         "id":"wei chunhua"      , "exp":250000]),
([ "name":"杨成协",         "id":"yang chengxie"      , "exp":300000]),
([ "name":"小欢",         "id":"xiao huan"      , "exp":25000]),
// ([ "name":"爱云残",         "id":"ai yuncan"      , "exp":25000]),
([ "name":"马善均",         "id":"ma shanjun"      , "exp":500000]),
([ "name":"王兴隆",         "id":"wang xinglong"      , "exp":500000]),
([ "name":"金乞儿",         "id":"jin qier"      , "exp":0]),
([ "name":"张召重",         "id":"zhang zhaozhong"      , "exp":10000000]),
([ "name":"文泰来",         "id":"wen tailai"      , "exp":10000000]),
([ "name":"绿营会众",         "id":"lvying huizhong"      , "exp":20000]),
([ "name":"成不优",         "id":"cheng buyou"      , "exp":1000000]),
([ "name":"封不平",         "id":"feng buping"      , "exp":1000000]),
([ "name":"陆大有",         "id":"lu dayou"      , "exp":10000]),
([ "name":"岳灵珊",         "id":"yue lingshan"      , "exp":10000]),
([ "name":"风清扬",         "id":"feng qingyang"      , "exp":15000000]),
([ "name":"小童",         "id":"xiaotong"      , "exp":2000]),
([ "name":"梁发",         "id":"liang fa"      , "exp":20000]),
([ "name":"江湖豪客",         "id":"jianghu haoke"      , "exp":2000]),
([ "name":"公平子",         "id":"gongping zi"      , "exp":60000]),
([ "name":"宁中则",         "id":"ning zhongze"      , "exp":900000]),
([ "name":"岳不群",         "id":"yue buqun"      , "exp":1000000]),
([ "name":"令狐冲",         "id":"linghu chong"      , "exp":50000]),
([ "name":"华山弟子",         "id":"dizi"      , "exp":2000]),
([ "name":"劳德诺",         "id":"lao denuo"      , "exp":15000]),

([ "name":"矮长老",         "id":"ai zhanglao"      , "exp":1500000]),
([ "name":"高长老",         "id":"gao zhanglao"      , "exp":1500000]),
([ "name":"牦牛",         "id":"mao niu"      , "exp":15000]),
([ "name":"绵羊",         "id":"sheep"      , "exp":5000]),
([ "name":"回族战士",         "id":"zhan shi"      , "exp":139039]),
([ "name":"霍青桐",         "id":"huo qingtong"      , "exp":600000]),
([ "name":"道鸟禅师",         "id":"daoniao npc"      , "exp":50000]),
([ "name":"土匪窝妓女",         "id":"ji nv"      , "exp":5000]),
([ "name":"诸葛不亮",         "id":"yaopu laoban"      , "exp":5000]),
([ "name":"澡堂老板",         "id":"zaotang laoban"      , "exp":5000]),
([ "name":"[1;33m男搓澡工[2;37;0m",         "id":"cuozao gong"      , "exp":150000]),
([ "name":"[1;33m女搓澡工[2;37;0m",         "id":"cuozao gong"      , "exp":150000]),
([ "name":"[1;33m方伯谦[2;37;0m",         "id":"fang boqian"      , "exp":1000000]),
([ "name":"[1;33m林国祥[2;37;0m",         "id":"lin guoxiang"      , "exp":1000000]),
([ "name":"灵鹫宫弟子",         "id":"dizi"      , "exp":10000]),
([ "name":"松鼠",         "id":"song shu"      , "exp":300]),
([ "name":"獐",         "id":"zhang"      , "exp":3000]),
([ "name":"梅花鹿",         "id":"meihua lu"      , "exp":3000]),
([ "name":"余婆婆",         "id":"yu popo"      , "exp":500000]),
([ "name":"程青霜",         "id":"cheng qingshuang"      , "exp":80000]),
([ "name":"石嫂",         "id":"shi sao"      , "exp":95000]),
([ "name":"符敏仪",         "id":"fu minyi"      , "exp":300000]),
([ "name":"竹剑",         "id":"zhu jian"      , "exp":500000]),
([ "name":"虚竹",         "id":"xu zhu"      , "exp":2500000]),
([ "name":"包万叶",         "id":"bao wanye"      , "exp":1000]),
([ "name":"褚万春",         "id":"chu wanchun"      , "exp":1657454]),

([ "name":"柯万钧",         "id":"ke wanjun"      , "exp":2010996]),

([ "name":"花万紫",         "id":"hua wanzi"      , "exp":1786108]),

([ "name":"耿万钟",         "id":"geng wanzhong"      , "exp":1870420]),
([ "name":"成自学",         "id":"cheng zixue"      , "exp":2019960]),

([ "name":"白万剑",         "id":"bai wanjian"      , "exp":2282042]),

([ "name":"李万山",         "id":"li wanshan"      , "exp":1000]),
([ "name":"白阿绣",         "id":"bai axiu"      , "exp":150952]),
([ "name":"[32m丫鬟[2;37;0m",         "id":"ya huan"      , "exp":800]),

([ "name":"闻万夫",         "id":"wen wanfu"      , "exp":1869720]),
([ "name":"苏万虹",         "id":"su wanhong"      , "exp":1816477]),
([ "name":"白自在",         "id":"bai zizai"      , "exp":5952259]),

([ "name":"梁自进",         "id":"liang zijin"      , "exp":1511126]),
([ "name":"封万里",         "id":"feng wanli"      , "exp":1399005]),
([ "name":"廖自砺",         "id":"liao zili"      , "exp":1516935]),
([ "name":"窈娘",         "id":"yao niang"      , "exp":10000]),
([ "name":"齐自勉",         "id":"qi zimian"      , "exp":2021754]),

([ "name":"呼延万善",         "id":"huyan wanshan"      , "exp":1555331]),

([ "name":"汪万翼",         "id":"wang wanyi"      , "exp":1760359]),

([ "name":"孙万年",         "id":"sun wannian"      , "exp":1000]),

([ "name":"徐元文",         "id":"xu yuanwen"      , "exp":3500]),

([ "name":"贾万玉",         "id":"jia wanyu"      , "exp":103316]),

([ "name":"小唐",         "id":"xiao tang"      , "exp":50000]),
([ "name":"西夏兵",         "id":"xixia bing"      , "exp":12000]),
([ "name":"太监",         "id":"taijian"      , "exp":1000]),
([ "name":"小伙计",         "id":"xiao huoji"      , "exp":400]),
([ "name":"宫女",         "id":"gongnv"      , "exp":1000]),
([ "name":"皇宫卫士",         "id":"wei shi"      , "exp":90000]),
([ "name":"西夏公主",         "id":"princess"      , "exp":0]),
([ "name":"校尉",         "id":"xiao wei"      , "exp":50000]),
([ "name":"[1;37m西夏[1;31m名商[2;37;0m",         "id":"xixia mingshang"      , "exp":1000]),
([ "name":"太医",         "id":"taiyi"      , "exp":1000]),
([ "name":"叶二娘",         "id":"ye erniang"      , "exp":300000]),
([ "name":"南海鳄神",         "id":"nanhai eshen"      , "exp":250000]),
([ "name":"云中鹤",         "id":"yun zhonghe"      , "exp":150000]),
([ "name":"玄真道长",         "id":"xuan zhen"      , "exp":950000]),
([ "name":"茶馆伙计",         "id":"chaguan huoji"      , "exp":1000]),
([ "name":"高彦超",         "id":"gao yanchao"      , "exp":40000]),
([ "name":"花老板",         "id":"hua laoban"      , "exp":1000]),
([ "name":"小丐",         "id":"xiao gai"      , "exp":20000]),
([ "name":"胡雪源",         "id":"hu xueyuan"      , "exp":50000]),
([ "name":"陈近南",         "id":"chen jinnan"      , "exp":12000000]),
([ "name":"马超兴",         "id":"ma chaoxing"      , "exp":1250000]),
([ "name":"书店老板",         "id":"shudian laoban"      , "exp":1000]),
([ "name":"唐老板",         "id":"tang laoban"      , "exp":1000]),
([ "name":"赵老板",         "id":"zhao laoban"      , "exp":1000]),
([ "name":"药铺伙计",         "id":"yaopu huoji"      , "exp":1000]),
([ "name":"鹿杖客",         "id":"luzhang ke"      , "exp":100000000]),
([ "name":"鹤笔翁",         "id":"hebi weng"      , "exp":100000000]),
([ "name":"贾老六",         "id":"jia laoliu"      , "exp":30000]),
([ "name":"媒婆",         "id":"mei_po"      , "exp":100000]),
([ "name":"小红娘",         "id":"xiao hongniang"      , "exp":3000]),
([ "name":"江耀亭",         "id":"jiang yaoting"      , "exp":30000]),
([ "name":"冷谦",         "id":"leng qian"      , "exp":100000]),
([ "name":"说不得",         "id":"shuo bude"      , "exp":100000]),
([ "name":"彭莹玉",         "id":"peng yingyu"      , "exp":100000]),
([ "name":"周颠",         "id":"zhou dian"      , "exp":100000]),
([ "name":"张中",         "id":"zhang zhong"      , "exp":100000]),
([ "name":"吴六破",         "id":"wu liupo"      , "exp":50000]),
([ "name":"周五输",         "id":"zhou wushu"      , "exp":50000]),
([ "name":"范遥",         "id":"fan yao"      , "exp":1000000]),
([ "name":"杨逍",         "id":"yang xiao"      , "exp":800000]),
([ "name":"小昭",         "id":"xiao zhao"      , "exp":50000]),
([ "name":"老者",         "id":"lao zhe"      , "exp":200000]),
([ "name":"男孩",         "id":"boy"      , "exp":100]),
([ "name":"农妇",         "id":"woman"      , "exp":200]),
([ "name":"老婆婆",         "id":"old woman"      , "exp":150]),
([ "name":"李天垣",         "id":"li tianyuan"      , "exp":100000]),
([ "name":"殷野王",         "id":"yin yewang"      , "exp":100000]),
([ "name":"穷汉",         "id":"poor man"      , "exp":250]),
([ "name":"王八衰",         "id":"wang bashuai"      , "exp":55000]),
([ "name":"郑七灭",         "id":"zheng qimie"      , "exp":55000]),
([ "name":"蝴蝶",         "id":"hu die"      , "exp":50]),
([ "name":"蜜蜂",         "id":"bee"      , "exp":0]),
([ "name":"钱二败",         "id":"qian erbai"      , "exp":50000]),
([ "name":"孙三毁",         "id":"sun sanhui"      , "exp":50000]),
([ "name":"赵一伤",         "id":"zhao yishang"      , "exp":50000]),
([ "name":"李四摧",         "id":"li sicui"      , "exp":50000]),
([ "name":"谢逊",         "id":"xie xun"      , "exp":500000]),
([ "name":"绿衣女郎",         "id":"girl"      , "exp":1000]),
([ "name":"严妈妈",         "id":"yan mama"      , "exp":50000]),
([ "name":"王夫人",         "id":"wang furen"      , "exp":80000]),
([ "name":"丫鬟",         "id":"ya huan"      , "exp":5000]),
([ "name":"阿碧",         "id":"a bi"      , "exp":13000]),
([ "name":"阿朱",         "id":"a zhu"      , "exp":13000]),
([ "name":"邓百川",         "id":"deng baichuan"      , "exp":500000]),
([ "name":"包不同",         "id":"bao butong"      , "exp":500000]),
([ "name":"庄丁",         "id":"zhuang ding"      , "exp":30000]),
([ "name":"风波恶",         "id":"feng boe"      , "exp":500000]),
([ "name":"慕容博",         "id":"murong bo"      , "exp":11000000]),
([ "name":"小童",         "id":"xiao tong"      , "exp":100]),
([ "name":"书生",         "id":"shu sheng"      , "exp":500000]),
([ "name":"婢女",         "id":"bi nu"      , "exp":10000]),
([ "name":"公冶乾",         "id":"gongye qian"      , "exp":500000]),
([ "name":"老者",         "id":"lao zhe"      , "exp":100]),
([ "name":"吴不知",         "id":"wu buzhi"      , "exp":10000]),
([ "name":"木人",         "id":"mu ren"      , "exp":50000]),
([ "name":"保镖",         "id":"bao biao"      , "exp":1276469]),
([ "name":"总管",         "id":"guan"      , "exp":721554]),
([ "name":"花农",         "id":"hua nong"      , "exp":3687]),
([ "name":"侍女",         "id":"shi nv"      , "exp":200]),
([ "name":"仆人",         "id":"pu ren"      , "exp":2000]),
([ "name":"柳随风",         "id":"liu suifeng"      , "exp":1200000]),
([ "name":"欧阳敏",         "id":"ouyang min"      , "exp":900000]),
([ "name":"小红",         "id":"xiao hong"      , "exp":500]),
([ "name":"小翠",         "id":"xiao cui"      , "exp":500]),
([ "name":"杨啸天",         "id":"yang xiaotian"      , "exp":1800000]),
([ "name":"阿萍",         "id":"ping"      , "exp":500]),
([ "name":"脚夫",         "id":"jiao fu"      , "exp":10500]),
([ "name":"梁柳鹤",         "id":"liang liuhe"      , "exp":1027943]),
([ "name":"妙回春",         "id":"miao huichun"      , "exp":500000]),
([ "name":"仆人",         "id":"puren"      , "exp":500]),
([ "name":"王贵",         "id":"wang gui"      , "exp":1200000]),
([ "name":"汤怀",         "id":"tang huai"      , "exp":1200000]),
([ "name":"张显",         "id":"zhang xian"      , "exp":1200000]),
([ "name":"周侗",         "id":"zhou tong"      , "exp":12500000]),
([ "name":"王二愣",         "id":"wang erleng"      , "exp":500]),
([ "name":"[32m翠姑[2;37;0m",         "id":"cui gu"      , "exp":6400]),
([ "name":"岳飞",         "id":"yue fei"      , "exp":3000000]),
([ "name":"志明长老",         "id":"zhiming zhanglao"      , "exp":1200000]),
([ "name":"汤洪氏",         "id":"tang hongshi"      , "exp":1000]),
([ "name":"汤永澄",         "id":"tang yongcheng"      , "exp":800000]),
([ "name":"村长",         "id":"cun zhang"      , "exp":102644]),
([ "name":"王裴氏",         "id":"wang peishi"      , "exp":1000]),
([ "name":"王明",         "id":"wang ming"      , "exp":1000]),
([ "name":"张老汉",         "id":"zhang laohan"      , "exp":9342]),
([ "name":"岳母",         "id":"yue mu"      , "exp":2000]),
([ "name":"张涛",         "id":"zhang tao"      , "exp":800000]),
([ "name":"张刘氏",         "id":"zhang liushi"      , "exp":1000]),
([ "name":"金丝雀",         "id":"sparrow"      , "exp":1000]),
([ "name":"道童",         "id":"daotong"      , "exp":2500]),
([ "name":"马钰",         "id":"ma yu"      , "exp":400000]),
([ "name":"刘处玄",         "id":"liu chuxuan"      , "exp":25000]),
([ "name":"浴堂道童",         "id":"daotong"      , "exp":3000]),
([ "name":"知客道长",         "id":"zhike daozhang"      , "exp":5000]),
([ "name":"孙不二",         "id":"sun buer"      , "exp":350000]),
([ "name":"[1;36m观想兽[2;37;0m",         "id":"guanxiang shou"      , "exp":0]),
([ "name":"张三",         "id":"zhang san"      , "exp":1000]),
([ "name":"骏马",         "id":"horse"      , "exp":100]),
([ "name":"谭处端",         "id":"tan chuduan"      , "exp":250000]),
([ "name":"程遥伽",         "id":"cheng yaojia"      , "exp":50000]),
([ "name":"王重阳",         "id":"wang chongyang"      , "exp":12000000]),

([ "name":"王处一",         "id":"wang chuyi"      , "exp":200000]),
([ "name":"丘处机",         "id":"qiu chuji"      , "exp":500000]),
([ "name":"郝大通",         "id":"hao datong"      , "exp":250000]),
([ "name":"赵志敬",         "id":"zhao zhijing"      , "exp":15000]),
([ "name":"王俊",         "id":"liangong dizi"      , "exp":2863]),
([ "name":"老者",         "id":"lao zhe"      , "exp":5000]),
([ "name":"烧火道士",         "id":"dao shi"      , "exp":1100]),

([ "name":"王福贵",         "id":"wang fugui"      , "exp":0]),
([ "name":"陆立鼎",         "id":"lu liding"      , "exp":30000]),
([ "name":"武修文",         "id":"wu xiuwen"      , "exp":30000]),
([ "name":"武敦儒",         "id":"wu dunru"      , "exp":30000]),
([ "name":"渔夫",         "id":"yu fu"      , "exp":1000]),
([ "name":"张阿生",         "id":"zhang asheng"      , "exp":1400000]),
([ "name":"巨鲸帮帮众",         "id":"bang zhong"      , "exp":5000]),
([ "name":"柯镇恶",         "id":"ke zhene"      , "exp":1400000]),
([ "name":"武三通",         "id":"wu santong"      , "exp":500000]),
([ "name":"全金发",         "id":"quan jinfa"      , "exp":1400000]),
([ "name":"包方圆",         "id":"bao fangyuan"      , "exp":0]),
([ "name":"阿根",         "id":"pu ren"      , "exp":500]),
([ "name":"乌鸦",         "id":"wuya"      , "exp":300]),
([ "name":"丑雕",         "id":"chou diao"      , "exp":80000]),
([ "name":"韩小莹",         "id":"han xiaoying"      , "exp":1400000]),
([ "name":"南希仁",         "id":"nan xiren"      , "exp":1400000]),
([ "name":"韩宝驹",         "id":"han baoju"      , "exp":1400000]),
([ "name":"陈阿婆",         "id":"chen apo"      , "exp":800]),
([ "name":"陈小二",         "id":"xiao fan"      , "exp":8000]),
([ "name":"农妇",         "id":"woman"      , "exp":10000]),
([ "name":"丁丁",         "id":"ding ding"      , "exp":1000]),
([ "name":"大黑",         "id":"dog"      , "exp":0]),
([ "name":"周彦钦",         "id":"zhou yanqin"      , "exp":1]),
([ "name":"玄惠大师",         "id":"xuanhui dashi"      , "exp":1000000]),
([ "name":"澄心",         "id":"chengxin luohan"      , "exp":500000]),
([ "name":"澄意",         "id":"chengyi luohan"      , "exp":500000]),
([ "name":"澄思",         "id":"chengsi luohan"      , "exp":500000]),
([ "name":"澄识",         "id":"chengshi luohan"      , "exp":500000]),
([ "name":"澄志",         "id":"chengzhi luohan"      , "exp":500000]),
([ "name":"净难",         "id":"xiao shami"      , "exp":500]),
([ "name":"玄难大师",         "id":"xuannan dashi"      , "exp":1000000]),
([ "name":"澄信",         "id":"chengxin luohan"      , "exp":500000]),
([ "name":"澄灵",         "id":"chengling luohan"      , "exp":500000]),
([ "name":"澄欲",         "id":"chengyu luohan"      , "exp":500000]),
([ "name":"澄尚",         "id":"chengshang luohan"      , "exp":500000]),
([ "name":"烧饭僧",         "id":"shaofan seng"      , "exp":2000]),
([ "name":"道一禅师",         "id":"daoyi chanshi"      , "exp":100000]),
([ "name":"扫地老僧",         "id":"hcc"      , "exp":2500000]),
([ "name":"慧真尊者",         "id":"huizhen zunzhe"      , "exp":200000]),
([ "name":"达摩老祖",         "id":"damo laozu"      , "exp":15000000]),
([ "name":"净悲",         "id":"xiao shami"      , "exp":500]),
([ "name":"玄悲大师",         "id":"xuanbei dashi"      , "exp":1000000]),
([ "name":"道正禅师",         "id":"daozheng chanshi"      , "exp":100000]),
([ "name":"进香客",         "id":"jingxiang ke"      , "exp":510]),
([ "name":"道相禅师",         "id":"daoxiang chanshi"      , "exp":100000]),
([ "name":"渡厄",         "id":"du e"      , "exp":2000000]),
([ "name":"渡劫",         "id":"du jie"      , "exp":2000000]),
([ "name":"渡难",         "id":"du nan"      , "exp":2000000]),
([ "name":"觉远大师",         "id":"jueyuan dashi"      , "exp":6400000]),
([ "name":"清乐比丘",         "id":"qingle biqiu"      , "exp":50000]),
([ "name":"净慈",         "id":"xiao shami"      , "exp":500]),
([ "name":"玄慈大师",         "id":"xuanci dashi"      , "exp":1000000]),
([ "name":"清法比丘",         "id":"qingfa biqiu"      , "exp":50000]),
([ "name":"清无比丘",         "id":"qingwu biqiu"      , "exp":50000]),
([ "name":"清为比丘",         "id":"qingwei biqiu"      , "exp":50000]),
([ "name":"清善比丘",         "id":"qingshan biqiu"      , "exp":30000]),
([ "name":"进香客",         "id":"jingxiang ke"      , "exp":505]),
([ "name":"守寺僧兵",         "id":"seng bing"      , "exp":10000]),
([ "name":"慧空尊者",         "id":"huikong zunzhe"      , "exp":200000]),
([ "name":"扫地僧",         "id":"saodi seng"      , "exp":5000]),
([ "name":"清闻比丘",         "id":"qingwen biqiu"      , "exp":50000]),
([ "name":"无名老僧",         "id":"wuming laoseng"      , "exp":30000000]),
([ "name":"慧如尊者",         "id":"huiru zunzhe"      , "exp":200000]),
([ "name":"慧合尊者",         "id":"huihe zunzhe"      , "exp":200000]),
([ "name":"慧修尊者",         "id":"huixiu zunzhe"      , "exp":200000]),
([ "name":"慧色尊者",         "id":"huise zunzhe"      , "exp":200000]),
([ "name":"慧虚尊者",         "id":"huixu zunzhe"      , "exp":200000]),
([ "name":"慧名尊者",         "id":"huiming zunzhe"      , "exp":200000]),
([ "name":"慧洁尊者",         "id":"huijie zunzhe"      , "exp":200000]),
([ "name":"虚呆",         "id":"xu dai"      , "exp":30000]),
([ "name":"清缘比丘",         "id":"qingyuan biqiu"      , "exp":50000]),
([ "name":"狱卒",         "id":"yu zu"      , "exp":20000]),
([ "name":"净痛",         "id":"xiao shami"      , "exp":500]),
([ "name":"玄痛大师",         "id":"xuantong dashi"      , "exp":1000000]),
([ "name":"执法僧兵",         "id":"seng bing"      , "exp":10000]),
([ "name":"澄观",         "id":"chengguan luohan"      , "exp":500000]),
([ "name":"澄知",         "id":"chengzhi luohan"      , "exp":500000]),
([ "name":"澄明",         "id":"chengming luohan"      , "exp":500000]),
([ "name":"澄净",         "id":"chengjing luohan"      , "exp":500000]),
([ "name":"净苦",         "id":"xiao shami"      , "exp":500]),
([ "name":"澄坚",         "id":"chengjian luohan"      , "exp":500000]),
([ "name":"玄苦大师",         "id":"xuanku dashi"      , "exp":1000000]),
([ "name":"澄行",         "id":"chengxing luohan"      , "exp":500000]),
([ "name":"澄寂",         "id":"chengji luohan"      , "exp":500000]),
([ "name":"澄灭",         "id":"chengmie luohan"      , "exp":500000]),
([ "name":"澄和",         "id":"chenghe luohan"      , "exp":500000]),
([ "name":"清观比丘",         "id":"qingguan biqiu"      , "exp":50000]),
([ "name":"虚明",         "id":"xu ming"      , "exp":20000]),
([ "name":"虚通",         "id":"xu tong"      , "exp":10000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":1000]),
([ "name":"护林僧兵",         "id":"seng bing"      , "exp":2000]),
([ "name":"进香客",         "id":"jingxiang ke"      , "exp":525]),
([ "name":"进香客",         "id":"jingxiang ke"      , "exp":520]),
([ "name":"进香客",         "id":"jingxiang ke"      , "exp":535]),
([ "name":"道果禅师",         "id":"daoguo chanshi"      , "exp":100000]),
([ "name":"道觉禅师",         "id":"daojue chanshi"      , "exp":100000]),
([ "name":"道成禅师",         "id":"daocheng chanshi"      , "exp":100000]),
([ "name":"道尘禅师",         "id":"daochen chanshi"      , "exp":100000]),
([ "name":"打铁僧",         "id":"datie seng"      , "exp":7500]),
([ "name":"虚劫",         "id":"xu jie"      , "exp":30000]),
([ "name":"道象禅师",         "id":"daoxiang chanshi"      , "exp":100000]),
([ "name":"清晓比丘",         "id":"qingxiao biqiu"      , "exp":50000]),
([ "name":"道品禅师",         "id":"daopin chanshi"      , "exp":100000]),
([ "name":"沐剑屏",         "id":"mu jianping"      , "exp":50000]),
([ "name":"方怡",         "id":"fang yi"      , "exp":50000]),
([ "name":"陆夫人",         "id":"lu furen"      , "exp":50000]),
([ "name":"船夫",         "id":"chuan fu"      , "exp":54810]),
([ "name":"苏州少女",         "id":"girl"      , "exp":70]),
([ "name":"苏州女孩",         "id":"girl"      , "exp":70]),
([ "name":"杨铁匠",         "id":"yang tiejiang"      , "exp":1000]),
([ "name":"孙剥皮",         "id":"sun baopi"      , "exp":50000]),
([ "name":"马夫",         "id":"ma fu"      , "exp":50000]),
([ "name":"过彦之",         "id":"guo yanzhi"      , "exp":50000]),
([ "name":"崔百全",         "id":"cui baiquan"      , "exp":50000]),
([ "name":"老夫子",         "id":"lao fuzi"      , "exp":40000]),
([ "name":"婢女",         "id":"bi nu"      , "exp":2000]),
([ "name":"票友",         "id":"piao you"      , "exp":14726]),
([ "name":"管事",         "id":"guan shi"      , "exp":1500]),
([ "name":"冯正东",         "id":"feng zhengdong"      , "exp":30000]),
([ "name":"甄有庆",         "id":"zhen youqing"      , "exp":30000]),
([ "name":"丫环",         "id":"ya huan"      , "exp":1000]),
([ "name":"老渠",         "id":"lao qu"      , "exp":100]),
([ "name":"尼姑",         "id":"ni gu"      , "exp":1000]),
([ "name":"小毛",         "id":"xiao mao"      , "exp":500000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":1007]),
([ "name":"不火不毛",         "id":"fefe man"      , "exp":400000]),
([ "name":"白衣武士",         "id":"wei shi"      , "exp":100000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":907]),
([ "name":"江百胜",         "id":"jiang baisheng"      , "exp":50000]),
([ "name":"青衣武士",         "id":"wei shi"      , "exp":60000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":691]),
([ "name":"小贩",         "id":"xiao fan"      , "exp":1000]),
([ "name":"红衣武士",         "id":"wei shi"      , "exp":80000]),
([ "name":"挑夫",         "id":"tiao fu"      , "exp":336]),
([ "name":"趟子手",         "id":"tangzi shou"      , "exp":10000]),
([ "name":"书生",         "id":"shu sheng"      , "exp":0]),
([ "name":"昆仑子",         "id":"fae shizhe"      , "exp":164034030]),
([ "name":"黄药师",         "id":"huang yaoshi"      , "exp":11000000]),
([ "name":"哑仆",         "id":"yapu"      , "exp":3743]),
([ "name":"船夫",         "id":"chuan fu"      , "exp":3000]),
([ "name":"周伯通",         "id":"zhou botong"      , "exp":20000000]),
([ "name":"傻姑",         "id":"sha gu"      , "exp":200000]),
([ "name":"程英",         "id":"cheng ying"      , "exp":400000]),
([ "name":"郭芙",         "id":"guo fu"      , "exp":500000]),
([ "name":"黄蓉",         "id":"huang rong"      , "exp":1500000]),
([ "name":"郭靖",         "id":"guo jing"      , "exp":2000000]),
([ "name":"本尘大师",         "id":"benchen dashi"      , "exp":50000]),
([ "name":"沙弥",         "id":"sha mi"      , "exp":3000]),
([ "name":"本参大师",         "id":"bencan dashi"      , "exp":80000]),
([ "name":"本因方丈",         "id":"benyin fangzhang"      , "exp":200000]),
([ "name":"孙拳",         "id":"sun quan"      , "exp":25000]),
([ "name":"枯荣大师",         "id":"kurong dashi"      , "exp":1500000]),
([ "name":"本观大师",         "id":"benguan dashi"      , "exp":100000]),
([ "name":"本相大师",         "id":"benxiang dashi"      , "exp":90000]),
([ "name":"地保",         "id":"dibao"      , "exp":2500]),
([ "name":"老大娘",         "id":"old woman"      , "exp":150]),
([ "name":"冯铁匠",         "id":"feng"      , "exp":50000]),
([ "name":"铁人",         "id":"tie ren"      , "exp":50000000]),
([ "name":"铁游夏",         "id":"tie youxia"      , "exp":10000000]),
([ "name":"青狼主",         "id":"judger"      , "exp":9000000]),
([ "name":"警卫",         "id":"guard"      , "exp":95000]),
([ "name":"小翠",         "id":"cui"      , "exp":1156]),
([ "name":"张翠山",         "id":"zhang cuishan"      , "exp":500000]),
([ "name":"小翠",         "id":"cui"      , "exp":1557]),
([ "name":"樵夫",         "id":"qiao fu"      , "exp":100]),
([ "name":"制香道长",         "id":"zhixiang daozhang"      , "exp":5000]),
([ "name":"道童",         "id":"daotong"      , "exp":2000]),
([ "name":"张松溪",         "id":"zhang songxi"      , "exp":500000]),
([ "name":"殷梨亭",         "id":"yin liting"      , "exp":500000]),
([ "name":"道士",         "id":"shaohuo daoshi"      , "exp":5000]),
([ "name":"白发老人",         "id":"baifa laoren"      , "exp":100000]),
([ "name":"俞莲舟",         "id":"yu lianzhou"      , "exp":800000]),
([ "name":"谷虚道长",         "id":"guxu daozhang"      , "exp":120000]),
([ "name":"宋远桥",         "id":"song yuanqiao"      , "exp":600000]),
([ "name":"进香客",         "id":"jinxiang ke"      , "exp":660]),
([ "name":"伐木道长",         "id":"famu daozhang"      , "exp":5000]),
([ "name":"进香客",         "id":"jinxiang ke"      , "exp":730]),
([ "name":"进香客",         "id":"jinxiang ke"      , "exp":470]),
([ "name":"进香客",         "id":"jinxiang ke"      , "exp":510]),
([ "name":"店小二",         "id":"xiao er"      , "exp":5000]),
([ "name":"张三丰",         "id":"zhang sanfeng"      , "exp":15000000]),
([ "name":"喜鹊",         "id":"xi que"      , "exp":300]),
([ "name":"俞岱岩",         "id":"yu daiyan"      , "exp":400000]),
([ "name":"进香客",         "id":"jinxiang ke"      , "exp":450]),
([ "name":"王语嫣",         "id":"wang yuyan"      , "exp":10000000]),
([ "name":"段誉",         "id":"duan yu"      , "exp":11861701]),
([ "name":"张 三",         "id":"zhang san"      , "exp":4000000]),
([ "name":"杜鹃",         "id":"pretty girl"      , "exp":200000]),
([ "name":"龙亦凡",         "id":"long yifan"      , "exp":5000000]),
([ "name":"[33m石破天[2;37;0m",         "id":"shi potian"      , "exp":8000000]),
([ "name":"[31m妙谛大师[2;37;0m",         "id":"miaodi dashi"      , "exp":1500000]),
([ "name":"[1;37m愚茶道长[2;37;0m",         "id":"yucha daozhang"      , "exp":1500000]),
([ "name":"[1;33m侠客岛使者[2;37;0m",         "id":"shi zhe"      , "exp":500000]),
([ "name":"[31m牧羊犬[2;37;0m",         "id":"muyang quan"      , "exp":5000]),
([ "name":"[37m绵羊[2;37;0m",         "id":"sheep"      , "exp":500]),
([ "name":"牧羊人",         "id":"muyang ren"      , "exp":1000]),
([ "name":"郭芙",         "id":"guo fu"      , "exp":100000]),
([ "name":"茶馆活计",         "id":"huo ji"      , "exp":1000]),
([ "name":"[1;36m赵老板[2;37;0m",         "id":"zhao laoban"      , "exp":10000]),
([ "name":"史春秋",         "id":"shi chunqiu"      , "exp":0]),
([ "name":"扬铁匠",         "id":"yang tiejiang"      , "exp":1000]),
([ "name":"铁匠铺伙计",         "id":"tiejianpu huoji"      , "exp":250]),
([ "name":"张铁匠",         "id":"zhang tiejiang"      , "exp":1000]),
([ "name":"襄阳守将",         "id":"shou jiang"      , "exp":100000]),
([ "name":"襄阳守军",         "id":"shou jun"      , "exp":20000]),
([ "name":"猎户",         "id":"lie hu"      , "exp":1000]),
([ "name":"崔掌柜",         "id":"cui zhanggui"      , "exp":10000]),
([ "name":"[31m蒙哥[2;37;0m",         "id":"meng ge"      , "exp":120000]),
([ "name":"蒙古亲兵",         "id":"qin bing"      , "exp":20000]),
([ "name":"中年女佣",         "id":"nvyong"      , "exp":1000]),
([ "name":"小兰",         "id":"xiao lan"      , "exp":1000]),
([ "name":"仕女",         "id":"shi nu"      , "exp":100]),
([ "name":"中年马夫",         "id":"ma fu"      , "exp":1000]),
([ "name":"蒙古牧民",         "id":"mu min"      , "exp":10000]),
([ "name":"蒙古妇女",         "id":"fu nu"      , "exp":1000]),
([ "name":"营门守将",         "id":"shou jiang"      , "exp":50000]),
([ "name":"营门守军",         "id":"shou jun"      , "exp":20000]),
([ "name":"老丈",         "id":"lao zhang"      , "exp":21000]),
([ "name":"李大哥",         "id":"li dage"      , "exp":10000]),
([ "name":"亲兵",         "id":"qin bing"      , "exp":2000]),
([ "name":"吕文德",         "id":"lv wende"      , "exp":100000]),
([ "name":"[32m歌妓[2;37;0m",         "id":"ge ji"      , "exp":100]),
([ "name":"[33m歌妓[2;37;0m",         "id":"ge ji"      , "exp":100]),
([ "name":"[31m歌妓[2;37;0m",         "id":"ge ji"      , "exp":100]),
([ "name":"[31m郭靖[2;37;0m",         "id":"guo jing"      , "exp":1800000]),
([ "name":"进香客",         "id":"jinxiang ke"      , "exp":610]),
([ "name":"[32m村姑[2;37;0m",         "id":"cun gu"      , "exp":800]),
([ "name":"白雕",         "id":"bai diao"      , "exp":150000]),
([ "name":"巡城守将",         "id":"shou jiang"      , "exp":100000]),
([ "name":"[35m程灵素[2;37;0m",         "id":"cheng lingsu"      , "exp":1000]),
([ "name":"[1;33m和服女子[2;37;0m",         "id":"hefu nvzi"      , "exp":150000]),
([ "name":"浴室招待",         "id":"zhaodai"      , "exp":100]),
([ "name":"礼品店小姐",         "id":"girl"      , "exp":5000000]),
([ "name":"驿站伙计",         "id":"huo ji"      , "exp":50000]),
([ "name":"阿凡提",         "id":"afanti"      , "exp":2500]),
([ "name":"阿拉木罕",         "id":"alamuhan"      , "exp":5000]),
([ "name":"波斯商人",         "id":"bosi shangren"      , "exp":6000]),
([ "name":"沙虫",         "id":"sha chong"      , "exp":300]),
([ "name":"买卖提",         "id":"maimaiti"      , "exp":50000]),
([ "name":"采药人",         "id":"caiyao ren"      , "exp":1000]),
([ "name":"[33m穷小贩[2;37;0m",         "id":"xiao fan"      , "exp":1000]),
([ "name":"清兵",         "id":"qing bing"      , "exp":500000]),
([ "name":"杨老板",         "id":"yang tiejiang"      , "exp":1000]),
([ "name":"忧国志士",         "id":"baixing"      , "exp":3894]),
([ "name":"凭吊者",         "id":"baixing"      , "exp":2754]),
});