mapping *kill_quest = ({
		([ "name":"张三丰",         "id":"zhang sanfeng"      ,]),
		([ "name":"灭绝师太",       "id":"miejue shitai"      ,]),
		([ "name":"洪七公",         "id":"hong qigong"        ,]),
		([ "name":"段誉",           "id":"duan yu"            ,]),
		([ "name":"陈近南",         "id":"chen jinnan"        ,]),
		([ "name":"王重阳",         "id":"wang chongyang"     ,]),
		([ "name":"武三通",         "id":"wu santong"         ,]),
		([ "name":"慧空尊者",       "id":"huikong zunzhe"     ,]),
		([ "name":"慧色尊者",       "id":"huise zunzhe"       ,]),
		([ "name":"慧真尊者",       "id":"huizhen zunzhe"     ,]),
		([ "name":"谷虚道长",       "id":"guxu daozhang"      ,]),
		([ "name":"宋远桥",         "id":"song yuanqiao"      ,]),
		([ "name":"张松溪",         "id":"zhang songxi"       ,]),
		([ "name":"俞莲舟",         "id":"yu lianzhou"        ,]),
		([ "name":"张翠山",         "id":"zhang cuishan"      ,]),
		([ "name":"何不净",         "id":"he bujing"          ,]),
		([ "name":"余洪兴",         "id":"yu hongxing"        ,]),
		([ "name":"李斧头",         "id":"li futou"           ,]),
		([ "name":"道成禅师",       "id":"daocheng chanshi"   ,]),
		([ "name":"道品禅师",       "id":"daopin chanshi"     ,]),
		([ "name":"道一禅师",       "id":"daoyi chanshi"      ,]),
		([ "name":"本观大师",       "id":"benguan dashi"      ,]),
		([ "name":"徐天川",         "id":"xu tianchuan"       ,]),
		([ "name":"宁中则",         "id":"ning zhongze"       ,]),
		([ "name":"丘处机",         "id":"qiu chuji"          ,]),
		([ "name":"马钰",           "id":"ma yu"              ,]),
		([ "name":"烧饭僧",         "id":"seng"								,]),
		([ "name":"虚通",           "id":"xu tong"						,]),
		([ "name":"虚明",           "id":"xu ming"						,]),
		([ "name":"清法比丘",       "id":"qingfa biqiu"				,]),
		([ "name":"守寺僧兵",       "id":"seng bing"					,]),
		([ "name":"清善比丘",       "id":"qingshan biqiu"			,]),
		([ "name":"巡山弟子",       "id":"xunshan dizi"				,]),
		([ "name":"文心师太",       "id":"wenxin shitai"			,]),
		([ "name":"文月师太",       "id":"wenyue shitai"			,]),
		([ "name":"文虚师太",       "id":"wenxu shitai"				,]),
		([ "name":"裘万家",         "id":"qiu wanjia"			    ,]),
		([ "name":"莫不收",         "id":"mo bushou"				  ,]),
		([ "name":"快活三",         "id":"kuaihuo san"				,]),
		([ "name":"本尘大师",       "id":"benchen dashi"			,]),
		([ "name":"本相大师",       "id":"benxiang dashi"			,]),
		([ "name":"本参大师",       "id":"bencan dashi"				,]),
		([ "name":"岳灵珊",         "id":"yue lingshan"				,]),
		([ "name":"梁发",           "id":"liang fa"						,]),
		([ "name":"尹志平",         "id":"yin zhiping"				,]),   
});
mapping *find_quest = ({
 (["name":"《广陵散》",            "id":"guangling san"					  ,]),
 (["name":HIR"日月神刀"NOR,        "id":"riyue dao"							  ,]),
 (["name":HIG"日月神剑"NOR,        "id":"riyue jian"							,]),
 (["name":"菩提子",                "id":"puti zi"								  ,]),
 (["name":HIB "冰魄杖" NOR,        "id":"bingpo zhang"						,]),
 (["name":"软猬甲",                "id":"ruanwei jia"						  ,]),
 (["name":YEL"九转熊胆丸"NOR,      "id":"shanling wan"						,]),
 (["name":"白衣",                  "id":"white"									  ,]),
 (["name":"淑女剑",                "id":"shunu sword"						  ,]),
 (["name":"叫化鸡",                "id":"jiaohua ji"							,]),
 (["name":YEL"女娲石"NOR,          "id":"nvwa shi"								,]),
 (["name":"老山参",                "id":"laoshan shen"						,]),
 (["name":"道德经「第十八章」",    "id":"jing"										,]),
 (["name":"无量寿经",              "id":"shu"										  ,]),
 (["name":"军服",                  "id":"junfu"									  ,]),
 (["name":GRN"玉竹杖"NOR,          "id":"yuzhu zhang"						  ,]),
 (["name":"红玫瑰",                "id":"red rose"								,]),
 (["name":"拂尘",                  "id":"fuchen"									,]),
 (["name":"普渡杖法",              "id":"shaolin wuji"						,]),
 (["name":"飞沙走石十三式",        "id":"blade book"							,]),
 (["name":"衙役服",                "id":"yayi cloth"							,]),
 (["name":"牢房钥匙",              "id":"laofang key"						  ,]),
 (["name":"雷震挡",                "id":"leizhendang"						  ,]),
 (["name":"天山雪莲",              "id":"xue lian"								,]),
 (["name":"道德经「第十三章」",    "id":"jing"										,]),
 (["name":"大金刚拳法",            "id":"shaolin wuji"						,]),
 (["name":HIR"苹果"NOR,            "id":"apple"									  ,]),
 (["name":HIY"香蕉"NOR,            "id":"banana"									,]),
 (["name":BLU"菠萝"NOR,            "id":"pineapple"							  ,]),
 (["name":HIY"橙子"NOR,            "id":"orange"									,]),
 (["name":HIG"西瓜"NOR,            "id":"watermelon"							,]),
 (["name":MAG"荔枝"NOR,            "id":"lichee"									,]),
 (["name":"旧竹片",                "id":"bamboo"									,]),
 (["name":"麻鞋",                  "id":"gunny shoes"						  ,]),
 (["name":"火折",                  "id":"fire"										,]),
 (["name":"熏田鸡",                "id":"tian ji"								  ,]),
 (["name":"好逑汤",                "id":"haoqiu tang"						  ,]),
 (["name":"六脉神剑剑谱",          "id":"liumai-shenjian jianpu"	,]),
 (["name":"粽子",                  "id":"zongzi"									,]),
 (["name":"少林英雄令",            "id":"yingxiong ling"					,]),
 (["name":"短剑",                  "id":"duanjian"								,]),
 (["name":HIC "『少林旅游图』" NOR,"id":"luyou tu"								,]),
});	