#pragma save_binary
#include <ansi.h>
inherit SKILL;

#define TIME 1000
#define EXP 120
#define POT 29

mapping *quest = ({
([      "quest":                "上官云",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "上官云",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "向问天",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "向问天",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),


([      "quest":                "黎生",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                HIR"日月神刀"NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                HIG"日月神剑"NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "杨逍",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "青色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                YEL"射雕英雄传"NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "宋远桥",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "灰色道袍",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "总管",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "总管",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "黑冠巨蟒",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "黑冠巨蟒",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "伏魔刀",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "金刚罩",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "菩提子",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "凌波微步图谱",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "北冥神功图谱",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                HIB "蓝玫瑰" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                HIB "黑郁金香" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               HIB "薄雪花" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "野风信子" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "玉白露" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "睡芙蓉" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "紫蔷薇" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "大丽花" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "勿忘我" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "白玫瑰" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "翡翠绿" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                HIB "雪腊梅" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "凌波微步图谱",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "《呕血谱》",
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "软猬甲",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "韦一笑",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "韦一笑",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "谢逊",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":               HIG "玄铁剑" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "程英",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":               "青色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "丘处机",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "陆乘风",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "清平剑",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "绿衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "菊剑",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "菊剑",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "张松溪",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "俞岱岩",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "张翠山",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "护院武师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "护院武师",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "黛绮丝",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "黛绮丝",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "紫色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "金花",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "殷天正",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "殷天正",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "浪回头",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "浪回头",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "欧阳敏",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
 ([      "quest":                "堂主令",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "玄难大师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "玄苦大师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "玄慈大师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "玄悲大师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "玄惠大师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               HIR"护法袈裟"NOR,   
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "封不平",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "封不平",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "成不优",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "成不优",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "岳不群",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "白色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "宁中则",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "紫色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "枯荣大师",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "保镖",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "保镖",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
