#pragma save_binary
#include <ansi.h>
inherit SKILL;

#define TIME 1000
#define EXP 75
#define POT 20

mapping *quest = ({
([      "quest":                "日月教众",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "日月教众",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "狱卒",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "黑衣",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "巡山弟子",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "莫不收",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "采花子",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "采花子",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "阿善",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "阿善",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "庄丁",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "庄丁",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "巴依",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "巴依",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "单刀",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "牢房钥匙",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "崔莺莺",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "崔莺莺",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "韦春芳",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "韦春芳",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "王五",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "王五",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "李余",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "李余",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "藏经阁道长",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "刘处玄",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "襄阳守军",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "郭没",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "老丈",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "老丈",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "卖艺人",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "卖艺人",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "土匪头",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "土匪头",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "土匪",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "土匪",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "小土匪",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "小土匪",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "仆人",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "仆人",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "虚明",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "虚通",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "劳德诺",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "陆大有",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "岳灵珊",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "绿色长裙",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":               "灰色长衫",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "梁发",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "信纸",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                MAG "紫霞秘籍" NOR,               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "手信",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "游龙剑",               
                "quest_type":           "寻",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "赵志敬",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "文虚师太",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
 ([      "quest":                "文心师太",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "文月师太",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "文怡师太",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "文闲师太",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "文善师太",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "裘万家",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "买卖提",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "买卖提",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "沈千盅",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "沈千盅",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "胡金科",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "胡金科",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "谢一绝",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "谢一绝",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "陈震骐",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "陈震骐",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "钟茗",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "钟茗",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "尹霜叶",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "尹霜叶",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "杨永福",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "杨永福",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "冯正东",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "冯正东",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "公子哥",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "公子哥",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "老夫子",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "老夫子",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

([      "quest":                "甄有庆",               
                "quest_type":           "胜",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),
([      "quest":                "甄有庆",               
                "quest_type":           "杀",
                "time":                 TIME,
                "exp_bonus":            EXP,
                "pot_bonus":            POT,
        ]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

