#include <ansi.h>
inherit SKILL;

mapping *quest = ({
        ([       "quest":               "霍都",
                "quest_type":           "杀",
                "time":  		700,
                "score"	:		10
        ]),
        ([      "quest":                "蒙古亲兵",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               12
        ]),
        ([      "quest":                "蒙古亲兵",
                "quest_type":           "胜",
                "time":                 600,
                "score" :               12
        ]),
        ([      "quest":                RED"蒙哥"NOR,
                "quest_type":           "杀",
                "time":                 600,
                "score" :               10
        ]),
        ([      "quest":                RED"蒙哥"NOR,
                "quest_type":           "胜",
                "time":                 600,
                "score" :               10
        ]),
        ([      "quest":                BLK"疯子"NOR,
                "quest_type":           "杀",
                "time":                 700,
                "score" :               10,
                "shen":			-10000
        ]),
        ([      "quest":                BLK"疯子"NOR,
                "quest_type":           "杀",
                "time":                 800,
                "score" :               10,
                "shen":			-10000
        ]),
        ([      "quest":                "吕文德",
                "quest_type":           "杀",
                "time":                 800,
                "score" :               10
        ]),  
        ([      "quest":                "吕文德",
                "quest_type":           "杀",
                "time":                 800,
                "score" :               10
        ]),
        ([      "quest":                "水靠",
                "quest_type":           "寻",
                "time":                 650,
                "score" :               8
        ]),
        ([      "quest":                "裘万家",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),
        ([      "quest":                "裘万家",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),
        ([      "quest":                "本相大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),    
         ([      "quest":                "本相大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),   
         ([      "quest":                "本参大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),   
        ([      "quest":                "本参大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "本观大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "本观大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "本因方丈",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),
        ([      "quest":                "本因方丈",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),
        ([      "quest":                "本尘大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),
        ([      "quest":                "本尘大师",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]), 
        ([      "quest":                "李斧头",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "李斧头",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "江上游",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]), 
        ([      "quest":                "江上游",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "快活三",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]), 
        ([      "quest":                "快活三",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "莫不收",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),  
        ([      "quest":                "莫不收",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),     
        ([      "quest":                "巡山弟子",
                "quest_type":           "杀",
                "time":                 560,
                "score" :               8
        ]),
        ([      "quest":                "巡山弟子",
                "quest_type":           "杀",
                "time":                 560,
                "score" :               8
        ]),
        ([      "quest":		"陆大有",               
                "quest_type":           "胜",
                "time":         	640,
                "score"	:		10
        ]),
        ([      "quest":		"令狐冲",               
                "quest_type":           "胜",
                "time":                 840,
                "score"	:		10
        ]),
        ([      "quest":                "官兵",
                "quest_type":           "胜",
                "time":                 300,
                "score" :               8
        ]),
        ([      "quest":                "官兵",
                "quest_type":           "胜",
                "time":                 300,
                "score" :               8
        ]),
        ([      "quest":                "阿善",
                "quest_type":           "胜",
                "time":                 300,
                "score" :               8
        ]),
        ([      "quest":                "阿善",
                "quest_type":           "胜",
                "time":                 300,
                "score" :               8
        ]),
        ([       "quest":              "谷虚道长",
                "quest_type":           "胜",
                "time":                 500,
                "score" :               8,
                "shen":			-30000
        ]),
        
        ([      "quest":                "阿紫",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               8
        ]),
        ([     "quest":                 "守山弟子",
                "quest_type":           "杀",
                "time":                 500,
                "score" :               10
        ]),       
        ([      "quest":                "游龙剑",
                "quest_type":           "寻",
                 "time":                 800,
                "score" :               8
        ]),  
         ([      "quest":              GRN"玉竹杖"NOR,
                "quest_type":           "寻",
                "time":                 800,
                "score" :               6
        ]),
        ([      "quest":                "霍都",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               10
        ]),
        ([      "quest":                "水靠",
                "quest_type":           "寻",
                "time":                 450,
                "score" :               8
        ]),
        ([      "quest":                "摘星子",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               10
        ]),
        ([      "quest":                "狮吼子",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               10
        ]),
        ([      "quest":                "巡山弟子",
                "quest_type":           "杀",
                "time":                 760,
                "score" :               7
        ]),
        ([      "quest":                "巡山弟子",
                "quest_type":           "杀",
                "time":                 760,
                "score" :               7
        ]),
        ([      "quest":		"孙不二",               
                "quest_type":           "胜",
                "time":  		900,
                "score"	:		10
        ]),
        ([      "quest":                "田伯光",
                "quest_type":           "杀",
                "time":                 900,
                "score" :               10
        ]),
        ([      "quest":                "闻苍松",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "裘万家",
                "quest_type":           "杀",
                "time":                 900,
                "score" :               10
        ]),
        
        ([      "quest":                "李莫愁",
                "quest_type":           "杀",
                "time":                 900,
                "score" :               10
        ]), 
        ([      "quest":                "李莫愁",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]), 
        ([      "quest":                "李莫愁",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                 "time":                 180,
                "score" :               7,
        ]),  
        ([      "quest":                "青色道袍",
                "quest_type":           "寻",
                "time":                 180,
                "score" :               7,
        ]),
        ([      "quest":                "青色道袍",
                "quest_type":           "寻",
                "time":                 180,
                "score" :               7,
        ]),       
         ([       "quest":               GRN"鞭法秘笈"NOR,
                "quest_type":           "寻",
                "time":                 800,
                "score" :               8
        ]),  
        ([      "quest":                "摘星子",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               8
        ]),
        ([      "quest":                "梁发",
                "quest_type":           "胜",
                "time":                 620,
                "score" :               8
        ]),    
        ([      "quest":		"颜垣",               
                "quest_type":           "胜",
                "time":  		900,
                "score"	:		10,
                "shen":			-30000
        ]),
        ([      "quest":                "庄铮",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "闻苍松",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "辛然",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "唐洋",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),    
        ([      "quest":                "庄铮",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "闻苍松",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "辛然",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "唐洋",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),          
        ([      "quest":		"谷虚道长",               
                "quest_type":           "胜",
                "time":  		900,
                "score"	:		10
        ]),
        ([      "quest":                "澄观",
                "quest_type":           "胜",
                "time":                 600,
                "score" :               13
        ]),
        ([      "quest":                "劳德诺",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),
        ([      "quest":                "宋青书",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),           
        ([      "quest":                RED"巨莽"NOR,               
                "quest_type":           "胜",
                "time":  		900,
                "score"	:		10
        ]),
        ([      "quest":                "官兵",
                "quest_type":           "杀",
                "time":                 900,
                "score" :               10
        ]),
        ([      "quest":                GRN"玉竹杖"NOR,
                "quest_type":           "寻",
                "time":                 800,
                "score" :               6
        ]),
        ([      "quest":                "霍都",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               10
        ]),
        ([      "quest":                RED"巨莽"NOR,               
                "quest_type":           "杀",
                "time":  		900,
                "score"	:		10
        ]),
        ([      "quest":                "官兵",
                "quest_type":           "杀",
                "time":                 900,
                "score" :               10
        ]),
        ([      "quest":                "闻苍松",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),
        ([      "quest":                "唐洋",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]), 
        ([      "quest":                "小昭",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			-30000
        ]),           
        ([      "quest":                "石板",
                "quest_type":           "寻",
                "time":                 950,
                "score" :               5,
        ]),  
        ([      "quest":                "圣火令",
                "quest_type":           "寻",
                "time":                 600,
                "score" :               10,
        ]),
        ([      "quest":                "江百胜",
                "quest_type":           "胜",
                "time":                 600,
                "score" :               8,
        ]),
        ([      "quest":                "江百胜",
                "quest_type":           "胜",
                "time":                 600,
                "score" :               8,
        ]),
        ([      "quest":                "江百胜",
                "quest_type":           "胜",
                "time":                 600,
                "score" :               8,
        ]),
        ([      "quest":                "韦春芳",
                "quest_type":           "杀",
                "time":                 400,
                "score" :               5
        ]),  
        ([      "quest":                "浪人头目",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               8
        ]),
        ([      "quest":                RED"土匪头"NOR,
                "quest_type":           "胜",
                "time":                 600,
                "score" :               10
        ]),
        ([      "quest":                BLK"土匪"NOR,
                "quest_type":           "杀",
                "time":                 600,
                "score" :               10
        ]), 
        ([      "quest":                "道一禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),   
        ([      "quest":                "道成禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),  
        ([      "quest":                "道尘禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),  
        ([      "quest":                "道相禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),  
        ([      "quest":                "道象禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),  
        ([      "quest":                "道觉禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),   
        ([      "quest":                "道品禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),  
        ([      "quest":                "道觉禅师",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10
        ]),  
        ([      "quest":                "史青山",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			5000
        ]), 
        ([      "quest":                "史青山",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			5000
        ]), 
        ([      "quest":                "陆冠英",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			5000
        ]),  
        ([      "quest":                "陈叁",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "王德",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]),     
       ([     	"quest":               	"金花",
                "quest_type":           "寻",
                "time":                 800,
                "score" :               6
        ]),
        ([      "quest":                "文凌师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "文善师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "文闲师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "文怡师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "文月师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "文心师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "文虚师太",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "小玲",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
        ([      "quest":                "小虹",
                "quest_type":           "胜",
                "time":                 900,
                "score" :               10,
                "shen":			1000
        ]), 
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
