#include <ansi.h>

inherit SKILL;

mapping *quest = ({
	([      "quest":                "浪人头目",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               8
        ]),
        ([      "quest":                "欧阳克",
                "quest_type":           "杀",
                "time":                 600,
                "score" :               8
        ]),
        ([      "quest":                "童百熊",
                "quest_type":           "杀",
                "time":                 800,
                "score" :               10
        ]),
        ([      "quest":                "鲍大楚",
                "quest_type":           "杀",
                "time":                 800,
                "score" :               10
        ]),
        ([      "quest":                "谢逊",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               15,
                "shen":			-50000
        ]),
        ([      "quest":                "韦一笑",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               15,
                "shen":			-50000
        ]),
        ([      "quest":                "黛绮丝",
                "quest_type":           "胜",
                  "time":                 500,
                "score" :               15,
                "shen":			-50000
        ]),
        ([      "quest":                "殷天正",
                "quest_type":           "胜",
                  "time":                 600,
                "score" :               15,
                "shen":			-50000
        ]),
        ([      "quest":                "马钰",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               12
        ]),
        ([      "quest":                "丘处机",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]),     
        ([      "quest":                "王处一",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               12
        ]),
        ([      "quest":                "刘处玄",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               12
        ]),
        ([      "quest":                "谭处端",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               12
        ]),
        ([      "quest":                "郝大通",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               12
        ]),
        ([      "quest":                "岳不群",
                "quest_type":           "胜",
                "time":                 300,
                "score" :               18
        ]),
        ([      "quest":                "护法袈裟",
                "quest_type":           "寻",
                "time":                 600,
                "score" :               9
        ]),
        ([      "quest":                "鲁有脚",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18
        ]),
        ([      "quest":                "宁中则",
                "quest_type":           "胜",
                "time":                 800,
                "score" :               15
        ]),
        ([      "quest":                "慧修尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧色尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧合尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧虚尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧名尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧洁尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧如尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]), 
        ([      "quest":                "慧空尊者",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12
        ]),
        ([      "quest":                "高长老",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			200000
        ]),
        ([      "quest":                "矮长老",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			200000
        ]),
        ([      "quest":                "成不优",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "封不平",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "封不平",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "彭有敬",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			-200000
        ]),
        ([      "quest":                "鲁有脚",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			-200000
        ]),
        ([      "quest":                "简长老",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			-200000
        ]),
        ([      "quest":                "简长老",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			-200000
        ]),
        ([      "quest":                "枯荣大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               12,
                "shen":			-200000
        ]),
        ([      "quest":                "王语嫣",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			-200000
        ]),
        ([      "quest":                "玄苦大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "玄难大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "玄慈大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "玄惠大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "玄痛大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "玄悲大师",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "渡难",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			200000
        ]),
        ([      "quest":                "渡劫",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			200000
        ]),
        ([      "quest":                "渡厄",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               18,
                "shen":			200000
        ]),
        ([      "quest":                "丁春秋",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               18,
                "shen":			-50000
        ]),
        ([      "quest":                "澄观",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄知",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄明",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄知",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄净",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄坚",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄行",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄寂",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄灭",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄和",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄尚",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄欲",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄灵",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄信",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄志",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄识",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄思",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄意",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "澄心",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               10,
                "shen":			200000
        ]),
        ([      "quest":                "俞莲舟",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               15,
                "shen":			200000
        ]),
        ([      "quest":                "张松溪",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "张翠山",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "殷梨亭",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "俞岱岩",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "张翠山",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "张松溪",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "宋远桥",
                "quest_type":           "胜",
                "time":                 700,
                "score" :               14,
                "shen":			200000
        ]),
        ([      "quest":                "吴三桂",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               20,
                "shen":			-200000
        ]),
        ([      "quest":                "保镖",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               15,
                "shen":			-200000
        ]),
        ([      "quest":                "保镖",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               15,
                "shen":			-200000
        ]),
        ([      "quest":                "护院武师",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               12,
                "shen":			-200000
        ]),
        ([      "quest":                "总管",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               12,
                "shen":			-200000
        ]),
        ([      "quest":                "吴应雄",
                "quest_type":           "杀",
                "time":                 700,
                "score" :               12,
                "shen":			-200000
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}