inherit SKILL;
mapping *quest = ({
      (["short":"天龙寺三元宫",       "place" :              "/d/tianlong/dadian",]),
      (["short":"扬州青竹林",       "place" :              "/d/city/ml1",]),
      (["short":"峨嵋山门",       "place" :              "/d/emei/shanmen",]),
      (["short":"扬州西门",       "place" :              "/d/city/ximen",]),
      (["short":"襄阳雪峰脚下",       "place" :              "/d/xiangyang/westr5",]),
      (["short":"苏州留园",       "place" :              "/d/suzhou/liuyuan",]),
      (["short":"苏州寒山寺",       "place" :              "/d/suzhou/hanshansi",]),
      (["short":"苏州立雪堂",       "place" :              "/d/suzhou/lixuetang",]),
      (["short":"苏州致爽阁",       "place" :              "/d/suzhou/zhishuang",]),
      (["short":"泉州向阳老宅",       "place" :              "/d/quanzhou/laozhai",]),
      (["short":"泉州码头",       "place" :              "/d/diaoyudao/matou0",]),
      (["short":"扬州中央广场",       "place" :              "/d/city/guangchang",]),
      (["short":"襄阳黑松岭",       "place" :              "/d/xiangyang/eroad5",]),
      (["short":"平西王府后花园",       "place" :              "/d/pingxiwangfu/garden",]),
      (["short":"黑沼小屋",       "place" :              "/d/yideng/yideng/yingguju",]),
      (["short":"星宿海",       "place" :              "/d/xingxiu/xxh1",]),
      (["short":"武当三清殿",         "place" :              "/d/wudang/sanqing",]),
      (["short":"峨嵋万年庵",       "place" :              "/d/emei/wannian",]),
      (["short":"峨嵋千佛庵大殿",       "place" :              "/d/emei/dadian",]),
      (["short":"峨嵋药王洞",       "place" :              "/d/emei/houshan/ywdong",]),
      (["short":"明教广场",       "place" :              "/d/mingjiao/guangchang",]),
      (["short":"明教碧水潭畔",       "place" :              "/d/mingjiao/bishuitanpan",]),
      (["short":"明教大沙漠",       "place" :              "/d/mingjiao/shamo7",]),
      (["short":"少林寺石阶",       "place" :              "/d/shaolin/shijie4",]),
      (["short":"汝州城",       "place" :              "/d/shaolin/ruzhou",]),
      (["short":"华山猢狲愁",       "place" :              "/d/huashan/husun",]),
      (["short":"华山玉女峰",       "place" :              "/d/huashan/yunu",]),
      (["short":"杀手帮清风堂",       "place" :              "/d/pker/qingfengtang",]),
      (["short":"杀手帮练武场",       "place" :              "/d/pker/wuchang1",]),
      (["short":"大理万劫谷",       "place" :              "/d/tianlong/gu",]),
      (["short":"扬州城北门",       "place" :              "/d/city/beimen",]),
      (["short":"襄阳帅府大厅",       "place" :              "/d/xiangyang/sfdating",]),
      (["short":"少林寺走廊",       "place" :              "/d/shaolin/zoulang7",]),
      (["short":"武当桃园小路",       "place" :              "/d/wudang/tyroad8",]),
      (["short":"少林寺般若堂九部",       "place" :              "/d/shaolin/banruo9",]),
      (["short":"日月朱雀堂",       "place" :              "/d/riyuejiao/zhuquetang",]),
      (["short":"六盘山",       "place" :              "/d/xingxiu/xxroad3",]),
      (["short":"丝绸之路",       "place" :              "/d/xingxiu/silk1",]),
      (["short":"汉水南岸",       "place" :              "/d/shaolin/hanshui1",]),
      (["short":"汉水北岸",       "place" :              "/d/shaolin/hanshui2",]),
      (["short":"天山脚下",       "place" :              "/d/xingxiu/shanjiao",]),
      (["short":"华山脚下",       "place" :              "/d/huashan/path1",]),
      (["short":"华山千尺幢",       "place" :              "/d/huashan/qianchi",]),
      (["short":"全真净人访",       "place" :              "/d/quanzhen/jingrenf",]),
      (["short":"全真凝雪阁",       "place" :                 "/d/quanzhen/ninglg",]),
      (["short":"陆家庄後院",       "place" :                 "/d/quanzhou/yuan", ]),
      (["short":"玉皇顶",        "place" :                "/d/taishan/yuhuang",]),
      (["short":"泰山柴门",       "place" :                 "/d/taishan/fefe8",        ]),
      (["short":"天山山路",       "place" :                 "/d/xingxiu/tianroad1",        ]),
      (["short":"嘉峪关",       "place" :                 "/d/xingxiu/jiayuguan",        ]),
      (["short":"月儿泉",       "place" :                 "/d/xingxiu/yueerquan",        ]),
      (["short":"巴依家客厅",       "place" :                 "/d/xingxiu/house1",        ]),
      (["short":"丐帮林间小屋",       "place" :                 "/d/city/gbxiaowu",        ]),
      (["short":"全真延灵阁",       "place" :                 "/d/quanzhen/yanlingg",        ]),
      (["short":"古墓大厅",       "place" :                 "/d/gumu/dating",        ]),
      (["short":"古墓小厅",       "place" :                 "/d/gumu/xiaoting",        ]),
      (["short":"铁枪庙",       "place" :                 "/d/quanzhou/tieqiang",        ]),
      (["short":"嘉兴南湖",       "place" :                 "/d/quanzhou/nanhu1",        ]),
      (["short":"牙山湾西口",       "place" :                 "/d/yashan/wanxi3",        ]),
      (["short":"牙山海边基地",       "place" :                 "/d/yashan/waneast3",        ]),
      (["short":"牙山小荒地",       "place" :                 "/d/yashan/wansouth3",        ]),
      (["short":"牙山驿道",       "place" :                 "/d/yashan/yidao3",        ]),
      (["short":"古墓侧室",        "place" :                 "/d/gumu/ceshi",        ]),
      (["short":"古墓断龙石",        "place" :                 "/d/gumu/duanlongshi",        ]),
      (["short":"终南山小溪",        "place" :                 "/d/gumu/xiaoxi",        ]),
      (["short":"终南山地下河",        "place" :                 "/d/gumu/dixiahe2",        ]),
      (["short":"少林石阶",        "place" :                 "/d/shaolin/shijie7",        ]),
      (["short":"归云庄后花园",        "place" :                 "/d/guiyunzhuang/houhuayuan",        ]),
      (["short":"归云庄练功房",        "place" :                 "/d/guiyunzhuang/liangongfang1",        ]),
      (["short":"归云庄炼丹房",        "place" :                 "/d/guiyunzhuang/danfang",        ]),
      (["short":"归云庄密林",        "place" :                 "/d/guiyunzhuang/milin1",        ]),
      (["short":"太湖阁",        "place" :                 "/d/guiyunzhuang/taihuge",        ]),
      (["short":"黑风山脚",        "place" :                 "/d/guiyunzhuang/shanlu1",        ]),
      (["short":"千尺幢",        "place" :                 "/d/huashan/qianchi",        ]),
      (["short":"泰山斗母宫",        "place" :                 "/d/taishan/doumo",        ]),
      (["short":"太湖街",        "place" :                 "/d/guiyunzhuang/taihujie",        ]),
      (["short":"嘉兴河岸",        "place" :                 "/d/quanzhou/river",        ]),
      (["short":"岳王墓忘忧亭",        "place" :                 "/d/yuewangmu/wangyouting",        ]),
      (["short":"岳王墓墓后空地",        "place" :                 "/d/yuewangmu/muhou",        ]),
      (["short":"少林藏经阁小屋",        "place" :                 "/d/shaolin/cjlou2",        ]),
      (["short":"扬州丽春院",        "place" :                 "/d/city/lichunyuan",        ]),
      (["short":"明教巨木坛",        "place" :                 "/d/mingjiao/jm-tan",        ]),
      (["short":"明教了望塔",        "place" :                 "/d/mingjiao/liaowang",        ]),
      (["short":"绿柳山庄小院",        "place" :                 "/d/mingjiao/yuan2",        ]),
      (["short":"星宿山谷口",        "place" :                 "/d/xingxiu/gu2",        ]),
      (["short":"扬州房产公司",        "place" :                 "/d/city/fangchan",        ]),
      (["short":"桃源驿路",        "place" :                 "/d/yideng/yideng/road2",        ]),
      (["short":"杀手帮山门",        "place" :                 "/adm/npc/shanmen",        ]),
      (["short":"大驿道",        "place" :                 "/d/taishan/yidao",        ]),
      (["short":"全真石阶",        "place" :                 "/d/quanzhen/shijie4",        ]),
      (["short":"无名谷底",        "place" :                 "/d/quanzhou/wuminggudi",        ]),
      (["short":"五里街",        "place" :                 "/d/taohuadao/wulijie1",        ]),
      (["short":"华山村南村口",        "place" :                 "/d/village/sexit",        ]),
      (["short":"华山村小巷尽头",        "place" :                 "/d/village/alley2",        ]),
      (["short":"星宿海",        "place" :                 "/d/xingxiu/xxh2",        ]),
      (["short":"天山脚下",        "place" :                 "/d/xingxiu/shanjiao",        ]),
      (["short":"丝绸之路",        "place" :                 "/d/xingxiu/silk2",        ]),
      (["short":"沙漠绿洲",        "place" :                 "/d/xingxiu/luzhou",        ]),
      (["short":"正气山庄",        "place" :                 "/d/city/shanzhuang",        ]),
      (["short":"醉仙楼二楼",        "place" :                 "/d/city/zuixianlou2",        ]),
      (["short":"洛阳中心广场",        "place" :                 "/d/luoyang/center",        ]),
      (["short":"赞普广场",        "place" :                 "/d/dalunsi/zanpugc",        ]),           


   

      });

mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
