
// the quest format is the following mapping:
 // exp :    type     name           id            objname  objid     time 

#include <ansi.h>
mapping quests_list = ([
   402 : ({ "kill","野狗",              "dog" ,  "",  "", "120" }),
   602 : ({ "kill","野兔",              "ye tu",  "",  "", "120" }), 
   802 : ({ "kill","小流氓",            "punk",  "",  "", "120" }),
   1012 : ({ "kill","流氓",               "liu mang", "","","120" }),
   4463 : ({ "kill",RED"火蛇"NOR,              "snake",  "",  "", "220" }),
   3402 : ({ "kill",HIC"眼镜蛇"NOR,       "snake",  "",  "", "230" }),
  3202 : ({ "kill","毒蛇",               "snake",   "",  "", "230" }), 
  3800 : ({ "kill","李铁嘴",             "fortune teller",   "",  "", "230" }),
  5882 : ({ "kill","小喽罗",            "xiao louluo",  "",  "", "230" }),
  5939 : ({ "kill","小土匪",             "xiao tufei", "","","230"}),
  1512 : ({ "kill","大狼狗",             "wolf dog" ,  "",  "", "230" }),
  5835 : ({ "kill","星宿派鼓手",               "gushou","","","220" }),
  4302 : ({ "kill",HBWHT+BLK"七寸子蛇"NOR,     "snake",   "",  "", "230" }),
  10032 : ({ "kill","日月教众",               "riyue jiaozhong", "","","300" }),
  9023 : ({ "kill","流氓头",               "liumang tou", "","","300" }),
  15020 : ({ "kill","打手",                 "da shou","","","300"}),
  10032 : ({ "kill","土匪",               "tufei",  "",  "", "300" }),
  57002 : ({ "kill","土匪头",               "tufei tou",  "",  "", "300" }),
  35002 : ({ "kill","崔员外",               "cui yuanwai", "","","300" }),
 56502 : ({ "kill","采花子",               "caihua zi",   "",  "", "500" }),
 80002 : ({ "kill","霍都",               "huo du",  "",  "", "500" }),
 141012 : ({ "kill","老虎",                 "tiger","","","500"}),
 18020 : ({ "kill","黑老板",                 "hei laoban","",  "", "500" }),
 132002 : ({ "kill",RED"巨蟒"NOR,               "ju mang", "",  "", "500" }),
 182002 : ({ "kill","田伯光",               "tian boguang","",  "", "500" }),
 283002 : ({ "kill","李莫愁",               "li mochou","",  "", "500" }),
 405002 : ({ "kill","摘星子",               "zhaixing zi", "",  "", "800" }),
 80022 : ({ "kill","鲍大楚",               "bao dachu", "",  "", "800" }),
 800002 : ({ "kill","秦伟邦",               "qin weibang","",  "", "800"  }),
560002 : ({ "kill","韦一笑",               "wei yixiao","",  "", "800" }),
150002 : ({ "kill","黑冠巨蟒",               "snake",  "",  "", "800" }),
2230002 : ({ "kill","丁春秋",               "ding chunqiu","",  "", "800" }),
710022 : ({ "kill","黛绮丝",               "dai qisi","",  "", "1000"  }),
 620022 : ({ "kill","谢逊",               "xie xun","",  "", "1000" }),
294002 : ({ "kill","任盈盈",               "ren yingying","",  "", "900"  }),
392002 : ({ "kill","秃笔翁",               "tubi weng","",  "", "900" }),
2300030 : ({ "kill","渡劫",               "du jie","",  "","920" }),
 1000002 : ({ "kill","向问天",               "xiang wentian","",  "","900"}),

101 : ({ "give","店小二",            "xiao er",  "花雕酒袋",  "jiudai", "120" }), 
    501 : ({ "give","老大娘",            "old woman",  "白银",  "silver", "120" }), 
    101 : ({ "give","老妇人",              "oldwoman" ,  "白银",  "silver", "120" }), 
    301 : ({ "give","地保",               "dibao" ,  "铁棍",  "tiegun", "120" }),
   3701 : ({ "give","赵狗儿",              "zhao gouer", "肥鸭","fei ya","120"}),
   501 : ({ "give","挑夫",              "tiao fu",  "手杖",      "walking stick", "180" }),      
    201 : ({ "give","小孩",              "kid" ,  "铜板",  "coin", "120" }),
   1101 : ({ "give","老农" ,              "lao nong","水壶","water bottle","120"}),
   1401 : ({ "give","卖艺人",                 "maiyi ren","白银","silver","120"}),
   2001 : ({ "give","进香客",            "jinxiang ke", "火折",    "fire", "120" }),
   3001 : ({ "give","挑夫",              "tiao fu",  "麻鞋",  "gunny shoes", "120" }),
   3201 : ({ "give","民女",              "min nv", "粉红绸衫", "pink cloth", "120"}),
     5101 : ({ "give","阿庆嫂",            "aqing sao", "水蜜桃", "tao", "200"}),
     7001 : ({ "give","阿善",                 "a shan","甜点心","dianxin","200"}),
  10001 : ({ "give","药铺伙计",          "yaopu huoji", "毒蛇胆", "shedan", "200" }),
  31001 : ({ "give","小贩",              "xiao fan",  "狗皮",  "gou pi", "200" }),
  52001 : ({ "give","牧羊人",             "muyang ren", "长鞭","changbian","200" }),
  53001 : ({ "give","林平之",               "lin pingzhi","华山剑谱","sword book","200"}),
 100001 : ({ "give","阿拉木罕",               "alamuhan", "天山雪莲","xue lian","200" }),
 110001 : ({ "give","管家",               "guan jia", "牢房钥匙","laofang key","400" }),
 120001 : ({ "give","澄识",                   "chengshi luohan","大般涅磐经",  "shu", "400" }), 
 150001 : ({ "give","李铁嘴",             "fortune teller",MAG "马屁宝典" NOR,"mapi baodian", "400" }),
 210001 : ({ "give","洪七公",              "hong qigong",GRN"玉竹杖"NOR,"yuzhu zhang", "400" }),  
220000 : ({ "give","裘万家",              "qiu wanjia","竹叶青","zhuye qing","600"}),
 240001 : ({ "give","王铁匠",             "wang tiejiang", "烧红的铁锤","hot hammer","400" }),
 305001 : ({ "give","游客",               "youke","野果","ye guo","400" }),
 320001 : ({ "give","波斯商人",               "bosi shangren","圣火令","shenghuo ling","400" }),
 330001 : ({ "give","道童",               "daotong", "拂尘","fuchen","400" }),
 334001 : ({ "give","本观大师",               "benguan dashi", "凌波微步图谱","lingbo-weibu", "400" }),
 520001 : ({ "give","慧修尊者",                "huixiu zunzhe","韦陀棍法",  "shaolin wuji", "500" }), 
 620001 : ({ "give","黄药师",               "huang yaoshi","洗髓经",  "book", "500"  }),

    200 : ({"find","珊瑚白菜",          "shanhu baicai",          "",       "",        " 60" }),
    240 : ({"find","扬州炒饭",          "yangzhou chaofan",          "",       "",        " 60" }),
    300 : ({"find","大还丹",            "dahuan dan",     "",       "",        "120" }),
    320 : ({"find","铁护腰",            "hu yao",         "",       "",        "120" }),
    350 : ({"find","金创药",            "jinchuang yao",          "",       "",        " 60" }),
    390 : ({"find","齐眉棍",            "qimei gun",      "",       "",        " 60" }),
    400 : ({"find",HIC "僧鞋" NOR,      "seng xie",     "",       "",        " 60" }),
    440 : ({"find","竹剑",              "zhujian",       "",       "",        " 60" }),//change
    450 : ({"find","铁手掌",            "iron hand",      "",       "",        " 60" }),
    540 : ({"find","包子",              "baozi",          "",       "",        "120" }), 
    550 : ({"find","烤鸡腿",            "jitui",          "",       "",        "120" }), 
    590 : ({"find","烤鸭",              "kaoya",          "",       "",        "120" }), 

    600 : ({"find","花雕酒袋",          "jiudai",         "",       "",        "120" }), 
   1010 : ({"find",HIC "『少林旅游图』" NOR,"luyou tu", "", "",        "120" }),
   1200 : ({"find","水壶",              "water bottle",   "",       "",        "120" }), 
   1250 : ({"find","旧竹片",            "bamboo",         "",       "",        " 60" }),
   1300 : ({"find","麻鞋",              "gunny shoes",    "",       "",        "120" }), 
   1500 : ({"find","火折",              "fire",       "",       "",        "120" }), 
   1600 : ({"find","熏田鸡",            "tian ji",        "",       "",        "200" }), 
   1610 : ({"find","好逑汤",            "haoqiu tang",    "",       "",        "200" }), 
   2000 : ({"find","六脉神剑剑谱",      "liumai-shenjian jianpu", "", "",    "160" }),          
   2100 : ({"find","粽子",              "zongzi",         "",       "",        "200" }), 
   2140 : ({"find","少林英雄令",        "yingxiong ling", "",       "",        "120" }), 
   2300 : ({"find","短剑",              "duanjian",       "",       "",        "120" }), 
   2330 : ({"find","臭鸭蛋",            "chou yadan",     "",       "",        "120" }), 
   2700 : ({"find","水蜜桃",            "tao",         "",       "",        "120" }),  //change
   5000 : ({"find","薄绢",              "silk",           "",       "",        " 60" }),
   5100 : ({"find","说文解字",          "shu",            "",       "",        "120" }), 
   6000 : ({"find","毒蛇胆",            "shedan",         "",       "",        "120" }), //kill snake
  10000 : ({"find","狗皮",              "gou pi",         "",       "",        "120" }), //kill 大狼狗
  50000 : ({"find","牢房钥匙",          "laofang key",    "",       "",        "120" }), //kill cui yuanwai
  51000 : ({"find","长鞭",              "changbian",           "",       "",        "120" }),  //change  kill alamuhan
  52000 : ({"find","水靠",              "shui kao",       "",       "",        "120" }), // dex>25
  57000 : ({"find","手信",              "letter",          "",       "",        "120" }), 
  58000 : ({"find","雷震挡",            "leizhendang",    "",       "",        "120" }), // kill 神剑八雄
 111000 : ({"find","大般涅磐经",        "shu",            "",       "",        "120" }), 
 120000 : ({"find","飞沙走石十三式",    "blade book", "",       "",        "120" }),     //bihua tian boguang
 210000 : ({"find",GRN"玉竹杖"NOR,      "yuzhu zhang","",       "",        "120" }),  //kill hu du
 220000 : ({"find","烧红的铁锤",        "hot hammer",     "",       "",        "120" }), //kill feng tiejiang
 250000 : ({"find",MAG "紫霞秘籍" NOR,  "zixia miji","",      "",        "120" }), 
 308000 : ({"find","凌波微步图谱",      "lingbo-weibu", "",       "",        "120" }), //dodge>100
 314000 : ({"find",HIW "雪腊梅" NOR,    "flower",     "",       "",        "120" }), //dodge>100
 320000 : ({"find","圣火令",            "shenghuo ling","",       "",        "500" }), 
 330000 : ({"find","拂尘",              "fuchen",         "",       "",        "500" }), //kill li mochou 
 517000 : ({"find","达摩剑法",          "shaolin wuji",     "",       "",        "500" }), 
 530000 : ({"find","伏魔刀",            "fumo dao",       "",       "",        "500" }), 
1020000 : ({"find","《广陵散》",      "guangling san",   "",       "",        "500" }),     
2010000 : ({"find",HIB "冰魄杖" NOR,    "bingpo zhang","",      "",        "500" }),      //  要求星宿派的
3100000 : ({"find",HIR"日月神刀"NOR,    "riyue dao",          "",       "",        "500" }), 

     502 : ({ "win","野狗",              "dog" ,  "",  "", "120" }),
   602 : ({ "win","野兔",              "ye tu",  "",  "", "120" }), 
   802 : ({ "win","小流氓",            "punk",  "",  "", "120" }),
   1012 : ({ "win","流氓",               "liu mang", "","","120" }),
   4463 : ({ "win",RED"火蛇"NOR,              "snake",  "",  "", "220" }),
   3402 : ({ "win",HIC"眼镜蛇"NOR,       "snake",  "",  "", "230" }),
  3202 : ({ "win","毒蛇",               "snake",   "",  "", "230" }), 
  3800 : ({ "win","李铁嘴",             "fortune teller",   "",  "", "230" }),
  5882 : ({ "win","小喽罗",            "xiao louluo",  "",  "", "230" }),
  5939 : ({ "win","小土匪",             "xiao tufei", "","","230"}),
  1512 : ({ "win","大狼狗",             "wolf dog" ,  "",  "", "230" }),
  5835 : ({ "win","星宿派鼓手",               "gushou","","","220" }),
  4302 : ({ "win",HBWHT+BLK"七寸子蛇"NOR,     "snake",   "",  "", "230" }),
  10032 : ({ "win","日月教众",               "riyue jiaozhong", "","","300" }),
  9023 : ({ "win","流氓头",               "liumang tou", "","","300" }),
  15020 : ({ "win","打手",                 "da shou","","","300"}),
  10032 : ({ "win","土匪",               "tufei",  "",  "", "300" }),
  57002 : ({ "win","土匪头",               "tufei tou",  "",  "", "300" }),
  35002 : ({ "win","崔员外",               "cui yuanwai", "","","300" }),
 56502 : ({ "win","采花子",               "caihua zi",   "",  "", "500" }),
 80002 : ({ "win","霍都",               "huo du",  "",  "", "500" }),
 141012 : ({ "win","老虎",                 "tiger","","","500"}),
 18020 : ({ "win","黑老板",                 "hei laoban","",  "", "500" }),
 132002 : ({ "win",RED"巨莽"NOR,               "ju mang", "",  "", "500" }),
 182002 : ({ "win","田伯光",               "tian boguang","",  "", "500" }),
 383002 : ({ "win","李莫愁",               "li mochou","",  "", "500" }),
 405002 : ({ "win","摘星子",               "zhaixing zi", "",  "", "800" }),
 80022 : ({ "win","鲍大楚",               "bao dachu", "",  "", "800" }),
 800002 : ({ "win","秦伟邦",               "qin weibang","",  "", "800"  }),
560002 : ({ "win","韦一笑",               "wei yixiao","",  "", "800" }),
150002 : ({ "win","黑冠巨蟒",               "snake",  "",  "", "800" }),
2230002 : ({ "win","丁春秋",               "ding chunqiu","",  "", "800" }),
710022 : ({ "win","黛绮丝",               "dai qisi","",  "", "1000"  }),
 620022 : ({ "win","谢逊",               "xie xun","",  "", "1000" }),
294002 : ({ "win","任盈盈",               "ren yingying","",  "", "900"  }),
392002 : ({ "win","秃笔翁",               "tubi weng","",  "", "900" }),
2300030 : ({ "win","渡劫",               "du jie","",  "","920" }),
 1000002 : ({ "win","向问天",               "xiang wentian","",  "","900"}),

]);
