string translate(string strSource)
{
        int newline = 0; 
        string line0 = ""; 
        string line1 = ""; 
        string line2 = ""; 
        string line3 = ""; 
        string line4 = ""; 
        string line5 = ""; 
        string space = "     "; 
        string *a; 
        string *b; 
        string *c; 
        string *d; 
        string *e; 
        string *f; 
        string *g;
        string *h; 
        string *I; 
        string *j; 
        string *k; 
        string *l; 
        string *m; 
        string *n; 
        string *o; 
        string *p; 
        string *q; 
        string *r; 
        string *s; 
        string *t; 
        string *u; 
        string *v; 
        string *w; 
        string *x; 
        string *y; 
        string *z; 
        string *zero ; 
        string *one  ; 
        string *two  ; 
        string *three; 
        string *four ; 
        string *five ; 
        string *six  ; 
        string *seven; 
        string *eight; 
        string *nine ;
        a[0] = "     ___  ";            
        a[1] = "    /   | ";            
        a[2] = "   / /| | ";            
        a[3] = "  / / | | ";            
        a[4] = " / /  | | ";            
        a[5] = "/_/   |_| ";
        b[0] = " _____  ";              
        b[1] = "|  _  \\ ";             
        b[2] = "| |_| | ";              
        b[3] = "|  _  { ";              
        b[4] = "| |_| | ";              
        b[5] = "|_____/ ";
        c[0] = " _____  ";              
        c[1] = "/  ___| ";              
        c[2] = "| |     ";              
        c[3] = "| |     ";              
        c[4] = "| |___  ";              
        c[5] = "\\_____| ";
        d[0] = " _____  ";              
        d[1] = "|  _  \\ ";             
        d[2] = "| | | | ";              
        d[3] = "| | | | ";              
        d[4] = "| |_| | ";              
        d[5] = "|_____/ ";
        e[0] = " _____  ";              
        e[1] = "| ____| ";              
        e[2] = "| |__   ";              
        e[3] = "|  __|  ";              
        e[4] = "| |___  ";              
        e[5] = "|_____| ";
        f[0] = " _____  ";              
        f[1] = "|  ___| ";              
        f[2] = "| |__   ";              
        f[3] = "|  __|  ";              
        f[4] = "| |     ";              
        f[5] = "|_|     ";
        g[0] = " _____  ";              
        g[1] = "/  ___| ";              
        g[2] = "| |     ";              
        g[3] = "| |  _  ";              
        g[4] = "| |_| | ";              
        g[5] = "\\_____/ ";
        h[0] = " _   _  ";              
        h[1] = "| | | | ";              
        h[2] = "| |_| | ";              
        h[3] = "|  _  | ";              
        h[4] = "| | | | ";              
        h[5] = "|_| |_| ";
        I[0] = " _  ";                  
        I[1] = "| | ";                  
        I[2] = "| | ";                  
        I[3] = "| | ";                  
        I[4] = "| | ";                  
        I[5] = "|_| ";
        j[0] = "     _  ";              
        j[1] = "    | | ";              
        j[2] = "    | | ";              
        j[3] = " _  | | ";              
        j[4] = "| |_| | ";              
        j[5] = "\\_____/ ";
        k[0] = " _   _   ";             
        k[1] = "| | / /  ";             
        k[2] = "| |/ /   ";             
        k[3] = "| |\\ \\   ";           
        k[4] = "| | \\ \\  ";           
        k[5] = "|_|  \\_\\ ";
        l[0] = " _      ";              
        l[1] = "| |     ";              
        l[2] = "| |     ";              
        l[3] = "| |     ";              
        l[4] = "| |___  ";              
        l[5] = "|_____| ";
        m[0] = "     ___  ___  ";       
        m[1] = "    /   |/   | ";       
        m[2] = "   / /|   /| | ";       
        m[3] = "  / / |__/ | | ";       
        m[4] = " / /       | | ";       
        m[5] = "/_/        |_| ";
        n[0] = " __   _  ";             
        n[1] = "|  \\ | | ";            
        n[2] = "|   \\| | ";            
        n[3] = "| |\\   | ";            
        n[4] = "| | \\  | ";            
        n[5] = "|_|  \\_| ";
        o[0] = " _____  ";              
        o[1] = "/  _  \\ ";             
        o[2] = "| | | | ";              
        o[3] = "| | | | ";              
        o[4] = "| |_| | ";              
        o[5] = "\\_____/ ";
        p[0] = " _____  ";              
        p[1] = "|  _  \\ ";             
        p[2] = "| |_| | ";              
        p[3] = "|  ___/ ";              
        p[4] = "| |     ";              
        p[5] = "|_|     ";
        q[0] = " _____    ";            
        q[1] = "/  _  \\   ";           
        q[2] = "| | | |   ";            
        q[3] = "| | | |   ";            
        q[4] = "| |_| |_  ";            
        q[5] = "\\_______| ";
        r[0] = " _____   ";             
        r[1] = "|  _  \\  ";            
        r[2] = "| |_| |  ";             
        r[3] = "|  _  /  ";             
        r[4] = "| | \\ \\  ";           
        r[5] = "|_|  \\_\\ ";
        s[0] = " _____  ";              
        s[1] = "/  ___/ ";              
        s[2] = "| |___  ";              
        s[3] = "\\___  \\ ";            
        s[4] = " ___| | ";              
        s[5] = "/_____/ ";
        t[0] = " _____  ";              
        t[1] = "|_   _| ";              
        t[2] = "  | |   ";              
        t[3] = "  | |   ";              
        t[4] = "  | |   ";              
        t[5] = "  |_|   ";
        u[0] = " _   _  ";              
        u[1] = "| | | | ";              
        u[2] = "| | | | ";              
        u[3] = "| | | | ";              
        u[4] = "| |_| | ";              
        u[5] = "\\_____/ ";
        v[0] = " _     _  ";            
        v[1] = "| |   / / ";            
        v[2] = "| |  / /  ";            
        v[3] = "| | / /   ";            
        v[4] = "| |/ /    ";            
        v[5] = "|___/     ";
        w[0] = " _          __ ";       
        w[1] = "| |        / / ";       
        w[2] = "| |  __   / /  ";       
        w[3] = "| | /  | / /   ";       
        w[4] = "| |/   |/ /    ";       
        w[5] = "|___/|___/     ";
        x[0] = "__    __ ";             
        x[1] = "\\ \\  / / ";           
        x[2] = " \\ \\/ /  ";           
        x[3] = "  }  {   ";             
        x[4] = " / /\\ \\  ";           
        x[5] = "/_/  \\_\\ ";
        y[0] = "__    __ ";             
        y[1] = "\\ \\  / / ";           
        y[2] = " \\ \\/ /  ";           
        y[3] = "  \\  /   ";            
        y[4] = "  / /    ";             
        y[5] = " /_/     ";
        z[0] = " ______ ";              
        z[1] = "|___  / ";              
        z[2] = "   / /  ";              
        z[3] = "  / /   ";              
        z[4] = " / /__  ";              
        z[5] = "/_____| ";
        zero[0] = " _____  ";           
        zero[1] = "/  _  \\ ";          
        zero[2] = "| | | | ";           
        zero[3] = "| |/| | ";           
        zero[4] = "| |_| | ";           
        zero[5] = "\\_____/ ";
        one[0] = " ___  ";              
        one[1] = "|_  | ";              
        one[2] = "  | | ";              
        one[3] = "  | | ";              
        one[4] = "  | | ";              
        one[5] = "  |_| ";
        two[0] = " _____  ";            
        two[1] = "/___  \\ ";           
        two[2] = " ___| | ";            
        two[3] = "/  ___/ ";            
        two[4] = "| |___  ";            
        two[5] = "|_____| ";
        three[0] = " _____  ";          
        three[1] = "|___  | ";          
        three[2] = "   _| | ";          
        three[3] = "  |_  { ";          
        three[4] = " ___| | ";          
        three[5] = "|_____/ ";
        four[0] = " _   _  ";           
        four[1] = "| | | | ";           
        four[2] = "| |_| | ";           
        four[3] = "\\___  | ";          
        four[4] = "    | | ";           
        four[5] = "    |_| ";
        five[0] = " _____  ";           
        five[1] = "|  ___| ";           
        five[2] = "| |___  ";           
        five[3] = "\\___  \\ ";         
        five[4] = " ___| | ";           
        five[5] = "\\_____| ";
        six[0] = " _____  ";            
        six[1] = "/  ___| ";            
        six[2] = "| |___  ";            
        six[3] = "|  _  \\ ";           
        six[4] = "| |_| | ";            
        six[5] = "\\_____/ ";
        seven[0] = " _____  ";          
        seven[1] = "|___  | ";          
        seven[2] = "    / / ";          
        seven[3] = "   / /  ";          
        seven[4] = "  / /   ";          
        seven[5] = " /_/    ";
        eight[0] = " _____  ";          
        eight[1] = "/  _  \\ ";         
        eight[2] = "| |_| | ";          
        eight[3] = "}  _  { ";          
        eight[4] = "| |_| | ";          
        eight[5] = "\\_____/ ";
        nine[0] = " _____  ";           
        nine[1] = "/  _  \\ ";          
        nine[2] = "| |_| | ";           
        nine[3] = "\\___  | ";          
        nine[4] = " ___| | ";           
        nine[5] = "|_____/ ";
//  string *strSource;
        for(i=0; i < sizeof(strSource); i++) {
                if(strSource[i] == " ") {line0 += space;          line1 += space;         line2 += space;         line3 += space;      line4 += space;      line5 += space}
                if(strSource[i] == "a") {line0 += a[0];                   line1 += a[1];                  line2 += a[2];              line3 += a[3];    line4 += a[4];     line5 += a[5]}
                if(strSource[i] == "b") {line0 += b[0];                   line1 += b[1];                  line2 += b[2];              line3 += b[3];    line4 += b[4];     line5 += b[5]}
                if(strSource[i] == "c") {line0 += c[0];                   line1 += c[1];                  line2 += c[2];              line3 += c[3];    line4 += c[4];     line5 += c[5]}
                if(strSource[i] == "d") {line0 += d[0];                   line1 += d[1];                  line2 += d[2];              line3 += d[3];    line4 += d[4];     line5 += d[5]}
                if(strSource[i] == "e") {line0 += e[0];                   line1 += e[1];                  line2 += e[2];              line3 += e[3];    line4 += e[4];     line5 += e[5]}
                if(strSource[i] == "f") {line0 += f[0];                   line1 += f[1];                  line2 += f[2];              line3 += f[3];    line4 += f[4];     line5 += f[5]}
                if(strSource[i] == "g") {line0 += g[0];                   line1 += g[1];                  line2 += g[2];              line3 += g[3];    line4 += g[4];     line5 += g[5]}
                if(strSource[i] == "h") {line0 += h[0];                   line1 += h[1];                  line2 += h[2];              line3 += h[3];    line4 += h[4];     line5 += h[5]}
                if(strSource[i] == "i") {line0 += I[0];                   line1 += I[1];                  line2 += I[2];              line3 += I[3];    line4 += I[4];     line5 += I[5]}
                if(strSource[i] == "j") {line0 += j[0];                   line1 += j[1];                  line2 += j[2];              line3 += j[3];    line4 += j[4];     line5 += j[5]}
                if(strSource[i] == "k") {line0 += k[0];                   line1 += k[1];                  line2 += k[2];              line3 += k[3];    line4 += k[4];     line5 += k[5]}
                if(strSource[i] == "l") {line0 += l[0];                   line1 += l[1];                  line2 += l[2];              line3 += l[3];    line4 += l[4];     line5 += l[5]}
                if(strSource[i] == "m") {line0 += m[0];                   line1 += m[1];                  line2 += m[2];              line3 += m[3];    line4 += m[4];     line5 += m[5]}
                if(strSource[i] == "n") {line0 += n[0];           line1 += n[1];                  line2 += n[2];                  line3 += n[3];    line4 += n[4];     line5 += n[5]}//              buildStyle2(inputText.substring((i+2),inputText.length),1);
         } else 
         {
                string outputText = line0+"\n"+line1+"\n"+line2+"\n"+line3+"\n"+line4+"\n"+line5;
//              if(booleanRepeat) {document.ascii.outputField.value += "\n"+outputText}
//              else {document.ascii.outputField.value = outputText}
         }
} 
