#include <ansi.h>
inherit NPC;
void create()
{
	set_name("鹏鹏",({"ppeng npc"}));
	set("long",0);
	set("title","[1;36m朝廷一品官员 [2;37;0m[1;33m辅国公[2;37;0m");
	set("age",160);
	set("str",35);
	set("con",27);
	set("int",30);
	set("spi",7);
	set("per",42);
	set("job_title","[1;33m武学大宗师[2;37;0m");
	set("nickname","。[2;37;0m[2;37;0m");
	set("combat_exp",101675088);
	set("max_qi",10397);
	set("max_jing",9981);
	set("gender","男性");
	set("max_neili",12340);
	set("max_jingli",11174);
	set("jiali",0);
	set("race","人类");
	set("class","officer");
	set("repute",8210157);
	set("score",1410);
	set("family/family_name","朝廷");
	set_skill("juemen-gun",863);
	set_skill("literate",830);
	set_skill("dodge",850);
	set_skill("huntian-qigong",757);
	set_skill("strike",760);
	set_skill("xianglong-zhang",814);
	set_skill("staff",836);
	set_skill("blade",84);
	set_skill("hand",195);
	set_skill("strategy",319);
	set_skill("sword",5);
	set_skill("identification",48);
	set_skill("xiaoyaoyou",821);
	set_skill("jinshe-jian",50);
	set_skill("dagou-bang",821);
	set_skill("parry",863);
	set_skill("force",831);
	set_skill("liuhe-dao",105);
	set_skill("hujia-daofa",8);
	set_skill("bixue-xinfa",349);
	set_skill("claw",9);
	set_skill("leadership",320);
	set_skill("unarmed",3);
	set_skill("shexing-shou",225);
	map_skill("dodge","juemen-gun");
	map_skill("strike","xianglong-zhang");
	map_skill("staff","dagou-bang");
	map_skill("parry","juemen-gun");
	map_skill("force","huntian-qigong");
	setup();
}
